<div class="card bg-dark">
  <div class="card-header border-bottom">
    <h4 class="text-center text-white">Szezonális</h4>
  </div>
  <div class="card-body">
    <div class="row">

      <!---------------------------------------------------------------------------->
      <div class="col-12">
        <div class="row border-bottom border-top bg-secondary">
          <div class="col-5">
            <div class="row">
              <div class="col-4 border-start border-end text-center">
                <a class="text-decoration-none" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday - 3)); ?>"><?= $days[$getday - 3]["name"]; ?></a>
              </div>
              <div class="col-4 border-end text-center">
                <a class="text-decoration-none" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday - 2)); ?>"><?= $days[$getday - 2]["name"]; ?></a>
              </div>
              <div class="col-4 border-end text-center">
                <a class="text-decoration-none" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday - 1)); ?>"><?= $days[$getday - 1]["name"]; ?></a>
              </div>
            </div>
          </div>
          <div class="col-2">
            <div class="row">
              <div class="col-12 border-end text-center">
                <a class="text-decoration-none text-warning" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday)); ?>"><?= $days[$getday]["name"]; ?></a>
              </div>
            </div>
          </div>
          <div class="col-5">
            <div class="row">
              <div class="col-4 border-end text-center">
                <a class="text-decoration-none" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday + 1)); ?>"><?= $days[$getday + 1]["name"]; ?></a>
              </div>
              <div class="col-4 border-end text-center">
                <a class="text-decoration-none" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday + 2)); ?>"><?= $days[$getday + 2]["name"]; ?></a>
              </div>
              <div class="col-4 border-end text-center">
                <a class="text-decoration-none" href="https://animem.org/Seasonal/<?= str_replace("-", "N", ($getday + 3)); ?>"><?= $days[$getday + 3]["name"]; ?></a>
              </div>
            </div>
          </div>
        </div>
        <div class="row border-bottom border-top bg-secondary mt-3">
          <div class="col-6">
            <div class="row">
              <div class="col-2 border-start border-end text-center">
                <span>#</span>
              </div>
              <div class="col-10 border-end text-center">
                <span>Cim</span>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="row">
              <div class="col-4 border-end text-center">
                <span>Feltőltve</span>
              </div>
              <div class="col-5 border-end text-center">
                <span>Feltöltő</span>
              </div>
              <div class="col-3 border-end text-center">
                <span data-bs-toggle="tooltip" data-bs-placement="top" title="A link megnyitását vagy a video megtekintését jelöli.">Megnézve<i class="text-danger">*</i>
                </span>
              </div>
            </div>
          </div>
        </div>

        <?php
        if (is_array($day) && !empty($day))
        {
          $i = 1;
          foreach ($day as $key => $value)
          {

            if ($value["for_link_use"] == 2 || $value["collector"] == 1)
            {
            }
            else
            {
        ?>
              <div class="row border-top bg-secondary opacity-75">
                <div class="col-6">
                  <div class="row h-100">
                    <div class="col-2 border-end text-center">
                      <span><?= $i++; ?>.</span>
                    </div>
                    <div class="col-10 border-end text-center text-truncate">
                      <span class="">
                        <a class="text-decoration-none <?= ($value["for_link_use"] == 1) ? "text-warning" : ""; ?>" href="<?= ($value["for_link_use"] == 1) ? "https://animem.org/Video/" . $value["id"] : "https://indavideo.hu/video/" . $value["link"]; ?>" target="<?= ($value["for_link_use"] == 1) ? "_self" : "_blank"; ?>">
                          <?= str_replace("-", " ", $value["title"]); ?>
                        </a>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="col-6">
                  <div class="row h-100">
                    <div class="col-4 border-end text-center">
                      <span><?= date("y. m. d. H:i ", strtotime($value["create_date"])); ?></span>
                    </div>
                    <div class="col-5 border-end text-center">
                      <span><a class="text-decoration-none <?= ($value["for_link_use"] == 1) ? "text-warning" : ""; ?>" href="https://animem.org/FanSub/<?= $value["uploaders_id"]; ?>" target="_blank"><?= $value["fname"]; ?></a></span>
                    </div>
                    <div class="col-3 text-center">
                      <span><?= ($value["viewed"] == NULL)?0:$value["viewed"]; ?>
                      </span>
                    </div>
                  </div>
                </div>
              </div>

          <?php
            }
          }
        }
        else
        {
          ?>
          <div class="row border-top bg-secondary opacity-75">
            <div class="col-12 text-center">
              <span>Nincs megjeleníthető tartalom! Válasz másik napot.</span>
            </div>
          </div>

        <?php
        } ?>
      </div>
    </div>
    <!---------------------------------------------------------------------------->
  </div>
</div>