<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-12">
      <a href="<?= BASEURL;?>" rel="home">
        <img src="<?= ASSETSURL;?>uploads/banner/other/Header.jpg" alt="" class="px-3" width="100%" height="250px">
      </a>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mx-3 px-3">
        <a class="navbar-brand" href="<?= BASEURL;?>Home">Kezdőlap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0">
            <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="<?= BASEURL;?>Anime/">Animék A-Z</a></li>
            <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="<?= BASEURL;?>statistic/">Statisztika</a></li>
            <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="https://hdfilmek.net">HD Filmek</a></li>
          </ul>
          <form action="/" method="GET" class="d-flex">
            <input class="form-control me-2" name="s" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-12">
      <div class="row mx-3">