
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="https://admin.animem.org/Assets/css/bootstrap.v5/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="https://admin.animem.org/Assets/css/bootstrap.v5/Superhero.min.css" type="text/css">
  <script src="https://admin.animem.org/Assets/Custom/assets/libs/bootstrap/dist/js/bootstrap.js"></script>
  <title>Animem.org - Uploaders Admin</title>
</head>

<body>