<?php

?>


<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="https://admin.animem.org/Assets/css/bootstrap.v5/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="https://admin.animem.org/Assets/css/bootstrap.v5/Superhero.min.css" type="text/css">
  <title>Search for indavideo</title>
</head>

<body>
  <div class="container">
    <div class="row my-3 justify-content-center">
      <div class="col-8 d-flex justify-content-center">
        <div class="card text-center ">
          <form class="form-horizontal" method="POST" id="form-id">
            <div class="card-body">
              <div class="row border-bottom mb-3">
                <div class="col-md-12 ">
                  <h4 class="card-title">Belépés</h4>
                </div>
              </div>
              <div class="row border-bottom">
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group row mb-1">
                        <label for="identification" class="col-sm-3 text-start control-label col-form-label">Csatorna azonosító</label>
                        <div class="col-sm-9">
                          <input type="text" class="form-control" name="identification" id="identification" placeholder="Csatorna azonosító" />
                        </div>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group row mb-1">
                        <label for="password" class="col-sm-3 text-start control-label col-form-label">Jelszó</label>
                        <div class="col-sm-9">
                          <input type="password" class="form-control" name="password" id="password" placeholder="Jelszó">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12  mb-1">
                <input type="submit" class="btn btn-primary btn-sm" value="Login">
              </div>
            </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</body>

</html>