<div class="container-fluid">
  <div class="row my-3">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="<?= BASEURL . "uploaders" .DS. "Home"; ?>"><?= $fname; ?></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<?= BASEURL . "uploaders" .DS. "Home"; ?>">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?= BASEURL . "uploaders" .DS. "Profil"; ?>">Profil</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?= BASEURL . "uploaders" .DS. "Statistic"; ?>">Statisztika</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?= BASEURL . "uploaders" .DS. ""; ?>">Adatlap igénylése</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?= BASEURL . "uploaders" .DS. ""; ?>">EpisodeList-ek kezelése</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?= BASEURL . "uploaders" .DS. "Logout"; ?>">Kilépés</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>