
      <div class="container-fluid mt-3">
        <div class="row mx-0">
          <div class="col-12 px-0">
            <nav class="navbar navbar-expand-lg navbar-light bg-light mt-0">
              <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand">Admin</a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="<?=  BASEURL; ?>episode.php">
                        EpisodeList
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="<?=  BASEURL; ?>uploaders.php">
                        Uploaders
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="<?=  BASEURL; ?>datasheet.php">
                        DataSheet
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="<?=  BASEURL; ?>blog.php">
                        Blog
                      </a>
                    </li>
                    <li class="nav-item me-2">
                      <form action="" method="get" id="formsearch">
                        <div class="input-group">
                          <input type="text" class="form-control" name="search" placeholder="Search" form="formsearch" value="<?= '' . $search . '';?>">
                          <button class="input-group-text" form="formsearch" type="submit">Search</button>
                        </div>
                      </form>
                    </li>
                    <li class="nav-item me-2">
                      <form action="" method="get" id="formnew">
                        <div class="input-group">
                          <input type="text" class="form-control" name="new" placeholder="New EpisodeList" form="formnew">
                          <button class="input-group-text" form="formnew" type="submit">New</button>
                        </div>
                      </form>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>


