<div class="card bg-dark">
  <div class="card-header border-bottom">
    <h4 class="text-center text-white">Belépés</h4>
  </div>
  <form class="form-horizontal" method="POST" id="form-id">
    <div class="card-body">
      <div class="row border-bottom">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12">
              <div class="form-group row mb-1">
                <label for="username" class="col-sm-3 text-start control-label col-form-label">Felhasználónév</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" name="username" id="username" placeholder="Felhasználónév" />
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group row mb-1">
                <label for="password" class="col-sm-3 text-start control-label col-form-label">Jelszó</label>
                <div class="col-sm-9">
                  <input type="password" class="form-control" name="password" id="password" placeholder="Jelszó">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6">
        <label class="d-grid gap-2 py-0">
        <button type="submit" class="btn btn-primary btn-sm border border-dark py-1">Login</button>
        </label>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6">
        <label class="d-grid gap-2 py-0">
          <a class="btn btn-secondary border border-dark py-1" href="https://animem.org/register">Regisztráció</a>
        </label>
      </div>
    </div>
  </form>
</div>