<div class="card bg-dark text-white">
	<div class="card-header border-bottom">
		<h4 class="text-center">Kezdőlap</h4>
	</div>
	<div class="card-body">

				<?= $statistic; ?>
</div>
	<div class="card-footer text-center">
	<!--h5>A fansub csapatok pontosabb statisztikát kaphatnak miután felvették velünk a kapcsolatott.</h5-->
	<i>- A statisztika rendszer még a tesztelés fázisban van. Ezért lehetnek hibák, késobbi változások, új adatok. -</i><br />
	<i>A statisztika rendszer 2022. 06. 20.-a óta műkődik.</i>

</div>
</div>