<div class="widget widget_text rapidwp-side-widget rapidwp-box">
  <div class="rapidwp-box-inside">
    <h2 class="rapidwp-widget-title">
      <span>MEGJELENÉSEK</span>
    </h2>
    <div class="textwidget custom-html-widget">
      <script>
        setInterval(function() {
          document.getElementById('cboxdiv').src = '//animem.org/mininews.php';
        }, 60000);
      </script>
      <div style="position: relative; margin: 0 auto; font-size: 0; line-height: 0;">
        <div style="position: relative; height: 272px; overflow: auto; overflow-y: auto; -webkit-overflow-scrolling: touch; border: 0px solid;">
          <iframe id="cboxdiv" src="//animem.org/mininews.php" marginheight="0" marginwidth="0" frameborder="0" width="100%" height="100%" scrolling="auto" allowtransparency="yes"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>