<div class="rapidwp-box-inside" style="margin-top:10px;">
  <header class="entry-header">
    <div class="entry-header-inside">
      <h1 class="entry-title">{{TITLE}}</h1>
    </div>
  </header>
  <div class="entry-content">
    <section style="display: block; vertical-align: top; text-align: center;">
    {{CONTENT}}
    </section>
  </div>
  <footer class="entry-footer" style="border-top:1px solid white;"></footer>
</div>