<div class="widget widget_text rapidwp-side-widget rapidwp-box">
  <div class="rapidwp-box-inside">
    <h2 class="rapidwp-widget-title">
      <span>Kiemelt FanSub-ok:</span>
    </h2>
    <div class="textwidget">
      <p style="vertical-align: top; text-align: center;">
              <!---------------------------------------------------------------------------->
              <?php
              $high = json_decode(file_get_contents("Config/banner/high.json"), true);
              foreach ($high as $block)
              {
              ?>
                <a href="<?= $block["link"]; ?>" target="_blank">
                  <img class="banner-<?= $block["size"]; ?>-<?= $block["type"]; ?>" title="<?= $block["name"]; ?>" alt="<?= $block["name"]; ?>" src="https://animem.org/Assets/uploads/banner/high/<?= $block["image"]; ?>">
                </a>
              <?php
              }
              ?>
              <!---------------------------------------------------------------------------->
      </p>
    </div>
  </div>
</div>