<!doctype html>
<html lang="hu">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="<?= BASEURL; ?>Assets/fontawesome/free/5.15.2/css/all.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>


  <title>Home</title>

  <style>
    .list tr {
      background-color: antiquewhite;
    }

    .list tr:first-child {
      background-color: burlywood;
    }

    .list tr:nth-child(2n) {
      background-color: darkseagreen;
    }

    .list tr:nth-child(3n)+tr {
      background-color: burlywood;
    }


    tr.collector,
    tr.collector span {
      color: deeppink;
    }

    tr.collector,
    tr.collector a {
      color: magenta;
    }

    tr.collector td,
    th {
      color: black;
    }

    .scroll {
      scrollbar-color: #444 rgba(0, 0, 0, 0.3);
      scrollbar-width: thin;
      overflow-x: hidden;
      overflow-y: auto;
    }

    .scroll::-webkit-scrollbar {
      width: 10px;
      background-color: #F5F5F5;
    }

    .scroll::-webkit-scrollbar-thumb {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
      background-color: #222;
    }

    .scroll::-webkit-scrollbar-track {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
      background-color: #F5F5F5;
    }
  </style>

</head>

<body class="scroll">
  <div class="container-fluid mt-3">
    <div class="row mx-0">
      <div class="col-12 px-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mt-0">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand">Admin</a>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="' . BASEURL . " episode.php" . '">
                        EpisodeList
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="' . BASEURL . "uploaders.php" . '">
                        Uploaders
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="' . BASEURL . "datasheet.php" . '">
                        DataSheet
                      </a>
                    </li>
                    <li class="nav-item me-2">
                      <form action="/uploaders.php" method="get" id="formsearch">
                        <div class="input-group">
                          <input type="text" class="form-control" name="search" placeholder="Search" form="formsearch" value="' . $search . '">
                          <button class="input-group-text" form="formsearch" type="submit">Search</button>
                        </div>
                      </form>
                    </li>
                    <li class="nav-item me-2">
                      <form action="/episode.php" method="get" id="formnew">
                        <div class="input-group">
                          <input type="text" class="form-control" name="new" placeholder="New EpisodeList" form="formnew">
                          <button class="input-group-text" form="formnew" type="submit">New</button>
                        </div>
                      </form>
                    </li>
                    <li class="nav-item me-2">
                      <form action="/uploaders.php" method="get" id="formuploaders">
                        <div class="input-group">
                          <input type="text" class="form-control" name="new" placeholder="New Uploaders" form="formuploaders">
                          <button class="input-group-text" form="formuploaders" type="submit">New</button>
                        </div>
                      </form>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>