<!DOCTYPE html>
<html lang="hu">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Animem | <?= $title; ?>">
  <meta property="og:image" content="https://animem.org/Assets/uploads/fontos_kepek/FaceBanner5.jpg">

  <meta name="description" content="Animem.org az animék országa. Az aninék országában szinte bármilyen animét megtalálhatsz. Legyen az szinkronos vagy feliratos. Mindezt a lehető legjobb minőségben.">
  <meta name="keywords" content="www.animem.org,animem.org,animem,anime,anime magyar,anime magyar felirattal,magyar felirat,magyarul,magyar,anime felirat,anime felirattal, anime, manga, magyar, fansub, felirat, videó, online, <?= $title; ?>">
  <meta name="robots" content="index,follow">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta property="og:url" content="https://animem.org/">
  <meta property="og:type" content="article">
  <meta property="og:title" content="Animem | <?= $title; ?> - Magyar Felirattal">
  <meta property="og:description" content="Animem.org az animék országa. Az aninék országában szinte bármilyen animét megtalálhatsz. Legyen az szinkronos vagy feliratos. Mindezt a lehető legjobb minőségben.">


  <link rel="icon" href="https://animem.org/Assets/uploads/fontos_kepek/32.jpg" sizes="32x32">
  <link rel="icon" href="https://animem.org/Assets/uploads/fontos_kepek/192.jpg" sizes="192x192">
  <link rel="apple-touch-icon" href="https://animem.org/Assets/uploads/fontos_kepek/180.jpg">

  <title>Animem | <?= $title; ?></title>

  <?php
  $image = ((time() % 2) == 0) ? "https://animem.org/Assets/uploads/fontos_kepek/background.jpg" : "https://animem.org/Assets/uploads/fontos_kepek/background2.jpg";
  ?>

  <script type="text/javascript">
  /*


    
    var x = setInterval(function()
    {
      var xmlhttp = new XMLHttpRequest();
      xmlhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
          console.log(this.responseText);

          document.getElementById("online_visior_val").innerHTML = this.responseText;
        }
      }
      xmlhttp.open("GET", "https://animem.org?get_online_visitor=online_visitor", true);
      xmlhttp.send();
    }, 10000);
  */
  </script>


  <style type="text/css">
    body.custom-background {
      background-image: url("<?= $image; ?>");
      background-position: left top;
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
    }

    .rapidwp-header-img-link::before {
      position: absolute;
      bottom: 5px;
      left: 5px;
      z-index: 10;
      content: url(/Assets/uploads/fontos_kepek/Logo-128.svg);
    }

    #iciripiciririczropicegyiciripiciririczropoiccalropizott {
      display: none;
    }

    #icipiciriczropic {
      display: block;
    }

    img.wp-smiley,
    img.emoji {
      display: inline !important;
      border: none !important;
      box-shadow: none !important;
      height: 1em !important;
      width: 1em !important;
      margin: 0 .07em !important;
      vertical-align: -0.1em !important;
      background: none !important;
      padding: 0 !important;
    }
  </style>

  <link rel="stylesheet" id="rapidwp-maincss-css" href="https://animem.org/Assets/rapidwp/style.css" type="text/css" media="all">


  <script type="text/javascript" src="https://animem.org/Assets/jquery/jquery.min.js" id="jquery-core-js"></script>
  <script type="text/javascript" src="https://animem.org/Assets/jquery/jquery-migrate.min.js" id="jquery-migrate-js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



  <style type="text/css" id="wp-custom-css">
    .cut-text {
      text-overflow: ellipsis;
      overflow: hidden;
      width: 160px;
      white-space: nowrap;
    }

    .div {
      display: inline-block;
      max-width: 190px;
      width: 190px;
      background-color: #1e1818;
      border-color: #00f;
      border-style: solid;
      border-width: 1px;
      border-bottom-width: 0px;
      margin: 5px;
      vertical-align: top;
      text-align: center;
    }

    .dive {
      padding: 5px;
      vertical-align: top;
      text-align: center;
      width: 100%;
    }





    body {
      color: white !important;
    }

    .message-2qnXI6 {
      font-weight: 600 !important;
      letter-spacing: 1px !important;
    }

    .blog-author span,
    .grid-1-author {
      font-style: normal;
    }

    .blog-author span {
      font-size: 14px
    }

    .blog-author {
      font-size: 16px;
    }

    .rapidwp-outer-wrapper {
      max-width: 95%;
      width: 100%;
    }

    .rapidwp-header-img {
      display: block;
      margin: 0 auto;
      width: 100%;
      border-top-left-radius: 6px !important;
      border-top-right-radius: 6px !important;
    }

    .rapidwp-primary-nav-menu a {
      color: white !important;
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif !important;
      letter-spacing: 0 !important;
      font-weight: 600 !important;
      font-size: 16px !important;
    }

    .rapidwp-box-inside {
      font-family: 'Karla', sans-serif;
      background: #212121 !important;
      border: 1px solid #212121 !important;
      border-radius: 6px !important;
    }

    .entry-header-inside {
      background: #212121 !important;
      border-bottom: 0px !important;
    }

    .entry-header {
      background: transparent !important;
      border-bottom: 1px solid#a8a8a8 !important;
    }

    .rapidwp-widget-title {
      background: #212121 !important;
    }

    .rapidwp-box {
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif !important;
      background: #212121 !important;
      border: 1px solid #212121 !important;
      border-radius: 6px !important;
    }

    .rapidwp-search-field {
      background: #363636 !important;
      border: 1px solid #171717 !important;
      color: white !important;
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif !important;
    }

    button,
    input[type=button],
    input[type=reset],
    input[type=submit] {
      border: 1px solid #171717 !important;
      color: #dbdbdb !important;
    }

    a {
      color: #dbdbdb !important;
      letter-spacing: 0.5px !important;
      text-decoration: none !important;
    }

    a.bluuuu {
      color: aqua !important;
      letter-spacing: 0.5px !important;
      text-decoration: none !important;
    }

    h1.astolfo {
      color: #f951b7 !important;
      letter-spacing: 0.5px !important;
      text-decoration: none !important;
    }

    p {
      color: #dbdbdb !important;
    }

    .rapidwp-widget-title {
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif !important;
      color: #dbdbdb !important;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif !important;
      color: #dbdbdb !important;
      letter-spacing: 0.2px !important;
    }

    .entry-content table {
      width: 100%;
      margin: 15px 0;
      border: 1px solid #ddd;
    }

    .entry-content table tr td {
      padding: 8px 10px;
      border-top: 1px solid #eee;
      border-right: 1px solid #eee;
      background: #4f4f4f;
      color: white;
    }

    .entry-content table tr:hover td,
    .entry-content table tr:focus td {
      background: #4f4f4f;
    }

    .entry-content table tr:nth-child(2n) td {
      background: #3d3d3d;
    }

    embed,
    iframe,
    object {
      width: 100% !important;
    }

    .blog .blog-title a {
      letter-spacing: 1.5px !important;
    }

    p.blog-short-content {
      letter-spacing: 0.5px !important;
    }

    .rapidwp-fp04-post .rapidwp-fp04-post-title a {
      color: #dbdbdb !important;
    }

    .rapidwp-page-header {
      background: #3d3d3d;
    }

    .entry-header {
      text-shadow: 0px 0px 0px !important;
    }

    .rapidwp-sidebar-widget-areas .widget .rapidwp-widget-title {
      text-shadow: 0px 0px 0px !important;
      font: 18px swald, Arial, Helvetica, sans-serif;
    }

    .column-1 span {
      font-size: 17px !important;
      font-weight: 700 !important;
      letter-spacing: 1px !important;
    }

    ul li {
      color: #dbdbdb !important;
      font-size: 14px;
      letter-spacing: 0.5px
    }

    .elementor-widget-container p span {
      font-size: 16px !important
    }

    .bdp-post-title {
      font-size: 20px;
    }

    .bdp-post-list {
      margin-bottom: 0px;
    }

    .wp-caption {
      background: #303030 !important;
    }

    .elementor-widget-container table a {
      color: #409bd4 !important;
      letter-spacing: 0.5px !important;
      text-decoration: none !important;
    }
  </style>
  <style>
    body {
      font-family: Arial;
    }

    /* Style the tab */
    .tab {
      overflow: hidden !important;
      border: 1px solid #ccc !important;
      background-color: #333 !important;
    }

    /* Style the buttons inside the tab */
    .tab button {
      background-color: inherit !important;
      float: left !important;
      border: none !important;
      outline: none !important;
      cursor: pointer !important;
      padding: 14px 16px !important;
      transition: 0.3s !important;
      font-size: 17px !important;
    }

    /* Change background color of buttons on hover */
    .tab button:hover {
      background-color: #222 !important;
    }

    /* Create an active/current tablink class */
    .tab button.active {
      background-color: #222 !important;
    }

    /* Style the tab content */
    .tabcontent {
      padding: 6px 12px !important;
      border: 1px solid #ffffff !important;
      border-top: none !important;
    }
  </style>
  <style>
    .tooltip {
      position: relative;
      display: inline-block;
    }

    .tooltip .tooltiptext {
      visibility: hidden;
      width: 120px;
      background-color: #555;
      color: #fff;
      text-align: center;
      border-radius: 6px;
      padding: 5px 0;
      position: absolute;
      z-index: 1;
      top: -125px;
      right: 105%;
      margin-left: -60px;
      opacity: 0;
      transition: opacity 0.3s;
    }

    .tooltip .tooltiptext::after {
      content: "";
      position: absolute;
      top: 100%;
      left: 50%;
      margin-left: -5px;
      border-width: 5px;
      border-style: solid;
      border-color: #555 transparent transparent transparent;
    }

    .tooltip:hover .tooltiptext {
      visibility: visible;
      opacity: 1;
    }
  </style>
  <style>
    .switch {
      position: relative;
      display: inline-block;
      vertical-align: top;
      width: 100px;
      height: 20px;
      padding: 3px;
      margin: 0 5px 5px 0;
      background: linear-gradient(to bottom, #eeeeee, #FFFFFF 25px);
      background-image: -webkit-linear-gradient(top, #eeeeee, #FFFFFF 25px);
      border-radius: 18px;
      box-shadow: inset 0 -1px white, inset 0 1px 1px rgba(0, 0, 0, 0.05);
      cursor: pointer;
      box-sizing: content-box;
    }

    .switch-input {
      position: absolute;
      top: 0;
      left: 0;
      opacity: 0;
      box-sizing: content-box;
    }

    .switch-label {
      position: relative;
      display: block;
      height: inherit;
      font-size: 12px;
      background: #eceeef;
      border-radius: inherit;
      box-sizing: content-box;
    }

    .switch-label:before,
    .switch-label:after {
      position: absolute;
      top: 50%;
      -webkit-transition: inherit;
      -moz-transition: inherit;
      -o-transition: inherit;
      transition: inherit;
      box-sizing: content-box;
    }

    .switch-label:before {
      content: attr(data-off);
      right: 11px;
      color: #523e3e;
    }

    .switch-label:after {
      content: attr(data-on);
      left: 11px;
      color: #FFFFFF;
      opacity: 0;
    }

    .switch-input:checked~.switch-label {
      background: #E1B42B;
    }

    .switch-input:checked~.switch-label:before {
      opacity: 0;
    }

    .switch-input:checked~.switch-label:after {
      opacity: 1;
    }

    .switch-handle {
      position: absolute;
      top: 4px;
      left: 4px;
      width: 28px;
      height: 28px;
      background: linear-gradient(to bottom, #FFFFFF 40%, #f0f0f0);
      background-image: -webkit-linear-gradient(top, #FFFFFF 40%, #f0f0f0);
      border-radius: 100%;
    }

    .switch-handle:before {
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -6px 0 0 -6px;
      width: 12px;
      height: 12px;
      background: linear-gradient(to bottom, #eeeeee, #FFFFFF);
      background-image: -webkit-linear-gradient(top, #eeeeee, #FFFFFF);
      border-radius: 6px;
    }

    .switch-input:checked~.switch-handle {
      left: 74px;
    }

    /* Transition
    ========================== */
    .switch-label,
    .switch-handle {
      transition: All 0.3s ease;
      -webkit-transition: All 0.3s ease;
      -moz-transition: All 0.3s ease;
      -o-transition: All 0.3s ease;
    }

    /* Sw itch Slide
    ==========================*/
    .switch-slide {
      padding: 0;
      margin: 5px 0 0;
      background: #eceeef;
      border-radius: 0;
      background-image: none;
    }

    .switch-slide .switch-label {
      box-shadow: none;
      background: none;
      overflow: hidden;
    }

    .switch-slide .switch-label:after,
    .switch-slide .switch-label:before {
      width: 100%;
      height: 65%;
      top: 0px;
      left: 0;
      text-align: center;
    }

    .switch-slide .switch-label:after {
      color: #FFFFFF;
      background: #181;
      left: -100px;
    }

    .switch-slide .switch-label:before {
      background: #eceeef;
    }

    .switch-slide .switch-handle {
      display: none;
    }

    .switch-slide .switch-input:checked~.switch-label {
      background: #181;
      border-color: #0088cc;
    }

    .switch-slide .switch-input:checked~.switch-label:before {
      left: 100px;
    }

    .switch-slide .switch-input:checked~.switch-label:after {
      left: 0;
    }
  </style>
  <style>
    body {
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }

    .topnav {
      overflow: hidden;
      background-color: #333;
    }

    .topnav a {
      float: left;
      display: block;
      color: #f2f2f2;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }

    .topnav a:hover {
      background-color: #000;
      color: black;
    }

    .topnav a.active {
      background-color: #04AA6D;
      color: white;
    }

    .topnav .icon {
      display: none;
    }

    @media screen and (max-width: 600px) {
      .topnav a:not(:first-child) {
        display: none;
      }

      .topnav a.icon {
        float: right;
        display: block;
      }
    }

    @media screen and (max-width: 600px) {
      .topnav.responsive {
        position: relative;
      }

      .topnav.responsive .icon {
        position: absolute;
        right: 0;
        top: 0;
      }

      .topnav.responsive a {
        float: none;
        display: block;
        text-align: left;
      }
    }
  </style>

</head>

<body class="custom-background">
  <div class="rapidwp-outer-wrapper">
    <div class="rapidwp-container" id="rapidwp-header" itemscope="itemscope" itemtype="http://schema.org/WPHeader" role="banner">
      <div class="rapidwp-head-content clearfix" id="rapidwp-head-content">
        <div class="rapidwp-header-image clearfix">
          <a href="https://animem.org/" rel="home" class="rapidwp-header-img-link">
            <img src="https://animem.org/Assets/uploads/fontos_kepek/header.jpg" width="1250" height="199" alt="" class="rapidwp-header-img">
          </a>
        </div>
        <div class="rapidwp-no-header-content">
          <p class="rapidwp-site-title"><a href="https://animem.org/" rel="home">Animem</a></p>
          <p class="rapidwp-site-description"><span></span></p>
        </div>
      </div>
    </div>
  </div>
  <div class="rapidwp-container rapidwp-primary-menu-container clearfix">
    <div class="rapidwp-outer-wrapper">
      <div class="rapidwp-primary-menu-container-inside clearfix">
        <div class="topnav" id="myTopnav">
          <a href="https://animem.org/">Kezdőlap</a>
          <!--a href="https://animem.org/animem-csapat/">Animem csapat</a-->
          <a href="https://www.twitch.tv/valorzoner">Driday-Fanzay</a>
          <a target="_blank" rel="noopener" href="https://hdfilmek.net/">HDFilmek.net</a>
          <a href="https://animem.org/animek-az/">Animék A-Z</a>
          <a href="https://animem.org/statistic/">Statisztika</a>
          <a href="javascript:void(0);" class="icon" onclick="myFunction2()">
            <i class="fa fa-bars"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div id="rapidwp-search-overlay-wrap" class="rapidwp-search-overlay">
    <button class="rapidwp-search-closebtn" aria-label="Close Search" title="Close Search">×</button>
    <div class="rapidwp-search-overlay-content">
      <form role="search" method="get" class="rapidwp-search-form" action="https://animem.org/">
        <label>
          <span class="screen-reader-text">Search for:</span>
          <input type="search" class="rapidwp-search-field" placeholder="Search …" value="<?= (isset($search) && !empty($search))?$search:""; ?>" name="s">
        </label>
        <input type="submit" class="rapidwp-search-submit" value="">
      </form>
    </div>
  </div>
  <div class="rapidwp-outer-wrapper">
    <div class="rapidwp-top-wrapper-outer clearfix">
      <div class="rapidwp-featured-posts-area rapidwp-top-wrapper clearfix">
        <div id="search-4" class="rapidwp-main-widget widget widget_search">
          <div class="rapidwp-box-inside">
            <form role="search" method="get" class="rapidwp-search-form" action="https://animem.org/Search">
              <label>
                <span class="screen-reader-text">Search for:</span>
                <input type="search" class="rapidwp-search-field" placeholder="Search …" value="<?= (isset($search) && !empty($search))?$search:""; ?>" name="s">
              </label>
              <input type="submit" class="rapidwp-search-submit" value="">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="rapidwp-outer-wrapper" style="transform: none;">
    <div class="rapidwp-container clearfix" style="transform: none;">
      <div class="rapidwp-content-wrapper clearfix">
        <div class="rapidwp-main-wrapper clearfix" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;" id="tekike">