<div class="widget widget_text rapidwp-side-widget rapidwp-box">
  <div class="rapidwp-box-inside">
    <figure class="wp-block-image size-full">
      <a href="https://www.twitch.tv/valorzoner" target="_blank">
        <img width="600" height="600" src="https://animem.org/Assets/uploads/fontos_kepek/FridayBanzay.gif" alt="Friday-Banzay Original GIF">
        <!--img width="600" height="600" src="https://cdn.discordapp.com/attachments/791772926608408577/943602370284253224/received_312880364198706.gif" alt="Friday-Banzay Actual Edition"-->
      </a>
      <figcaption>
        <strong>
          <a rel="noreferrer noopener" href="https://www.patreon.com/animem" target="_blank">
            <img style="width: 700px;" src="https://animem.org/Assets/uploads/fontos_kepek/Patreon.jpg" alt="">
          </a>
        </strong>
      </figcaption>
    </figure>
  </div>
</div>