<!------------------------------------------------------------->
<div class="widget widget_text rapidwp-side-widget rapidwp-box">
  <div class="rapidwp-box-inside">
    <h2 class="rapidwp-widget-title">
      <span>Csatlakozz a közzöséghez:</span>
    </h2>
    <div class="textwidget">
      <p style="vertical-align: middle; text-align: center;margin-bottom:0;">
        <a href="//animem.org/Discord" target="_blank">
          <img class="banner-1x1-small" title="Discord" alt="Discord" src="https://animem.org/Assets/uploads/banner/other/Discord.jpg">
        </a>
        <a href="//facebook.com/animem.org" target="_blank">
          <img class="banner-1x1-small" title="Facebook" alt="Facebook" src="https://animem.org/Assets/uploads/banner/other/Facebook.jpg">
        </a>
        <a href="//instagram.com/animem_hun" target="_blank">
          <img class="banner-1x1-small" title="Instagram" alt="Instagram" src="https://animem.org/Assets/uploads/banner/other/Instagram.jpg">
        </a>
      </p>
    </div>
  </div>
</div>
<!------------------------------------------------------------->