<!DOCTYPE html>
<html lang="hu">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Animem | <?= (isset($title)&& !empty($title))?$title:""; ?>">
  <meta property="og:image" content="https://animem.org/Assets/uploads/fontos_kepek/FaceBanner5.jpg">
  <link rel="stylesheet" href="https://animem.org/Assets/fontawesome-free-5.15.2-web/css/all.min.css">
  <meta name="description" content="Animem.org az animék országa. Az animék országában szinte bármilyen animét megtalálhatsz. Legyen az szinkronos vagy feliratos. Mindezt a lehető legjobb minőségben.">
  <meta name="keywords" content="www.animem.org,animem.org,animem,anime,anime magyar,anime magyar felirattal,magyar felirat,magyarul,magyar,anime felirat,anime felirattal, anime, manga, magyar, fansub, felirat, videó, online, <?= (isset($title)&& !empty($title))?$title:""; ?>">
  <meta name="robots" content="index,follow">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta property="og:url" content="https://animem.org/">
  <meta property="og:type" content="article">
  <meta property="og:title" content="Animem | <?= (isset($title)&& !empty($title))?$title:""; ?> - Animék Magyar Felirattal">
  <meta property="og:description" content="Animem.org az animék országa. Az animék országában szinte bármilyen animét megtalálhatsz. Legyen az szinkronos vagy feliratos. Mindezt a lehető legjobb minőségben.">

  <link rel="stylesheet" href="https://cdn.plyr.io/3.7.3/plyr.css">
  <script src="https://cdn.plyr.io/3.7.3/plyr.polyfilled.js"></script>
  <link rel="icon" href="https://animem.org/Assets/uploads/fontos_kepek/32.jpg" sizes="32x32">
  <link rel="icon" href="https://animem.org/Assets/uploads/fontos_kepek/192.jpg" sizes="192x192">
  <link rel="apple-touch-icon" href="https://animem.org/Assets/uploads/fontos_kepek/180.jpg">

  <title>Animem | <?= (isset($title) && !empty($title))?$title:""; ?></title>



  <script type="text/javascript" src="https://animem.org/Assets/jquery/jquery.min.js" id="jquery-core-js"></script>
  <script type="text/javascript" src="https://animem.org/Assets/jquery/jquery-migrate.min.js" id="jquery-migrate-js"></script>


  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  




  <style>
    .title {
position:absolute;
      top: 5px;
      left: 5px;
color:#fff;
      z-index: 10;
padding:20px;
}
.plyr--hide-controls .title {
    opacity: 0;
    pointer-events: none;
}
.plyr--hide-controls .button {
    opacity: 0;
    pointer-events: none;
}
    .switch {
      position: relative;
      display: inline-block;
      vertical-align: top;
      width: 100px;
      height: 20px;
      padding: 3px;
      margin: 0 5px 5px 0;
      background: linear-gradient(to bottom, #eeeeee, #FFFFFF 25px);
      background-image: -webkit-linear-gradient(top, #eeeeee, #FFFFFF 25px);
      border-radius: 18px;
      box-shadow: inset 0 -1px white, inset 0 1px 1px rgba(0, 0, 0, 0.05);
      cursor: pointer;
      box-sizing: content-box;
    }

    .switch-input {
      position: absolute;
      top: 0;
      left: 0;
      opacity: 0;
      box-sizing: content-box;
    }

    .switch-label {
      position: relative;
      display: block;
      height: inherit;
      font-size: 12px;
      background: #eceeef;
      border-radius: inherit;
      box-sizing: content-box;
    }

    .switch-label:before,
    .switch-label:after {
      position: absolute;
      top: 50%;
      -webkit-transition: inherit;
      -moz-transition: inherit;
      -o-transition: inherit;
      transition: inherit;
      box-sizing: content-box;
    }

    .switch-label:before {
      content: attr(data-off);
      right: 11px;
      color: #523e3e;
    }

    .switch-label:after {
      content: attr(data-on);
      left: 11px;
      color: #FFFFFF;
      opacity: 0;
    }

    .switch-input:checked~.switch-label {
      background: #E1B42B;
    }

    .switch-input:checked~.switch-label:before {
      opacity: 0;
    }

    .switch-input:checked~.switch-label:after {
      opacity: 1;
    }

    .switch-handle {
      position: absolute;
      top: 4px;
      left: 4px;
      width: 28px;
      height: 28px;
      background: linear-gradient(to bottom, #FFFFFF 40%, #f0f0f0);
      background-image: -webkit-linear-gradient(top, #FFFFFF 40%, #f0f0f0);
      border-radius: 100%;
    }

    .switch-handle:before {
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -6px 0 0 -6px;
      width: 12px;
      height: 12px;
      background: linear-gradient(to bottom, #eeeeee, #FFFFFF);
      background-image: -webkit-linear-gradient(top, #eeeeee, #FFFFFF);
      border-radius: 6px;
    }

    .switch-input:checked~.switch-handle {
      left: 74px;
    }

    /* Transition
    ========================== */
    .switch-label,
    .switch-handle {
      transition: All 0.3s ease;
      -webkit-transition: All 0.3s ease;
      -moz-transition: All 0.3s ease;
      -o-transition: All 0.3s ease;
    }

    /* Sw itch Slide
    ==========================*/
    .switch-slide {
      padding: 0;
      margin: 5px 0 0;
      background: #eceeef;
      border-radius: 0;
      background-image: none;
    }

    .switch-slide .switch-label {
      box-shadow: none;
      background: none;
      overflow: hidden;
    }

    .switch-slide .switch-label:after,
    .switch-slide .switch-label:before {
      width: 100%;
      height: 65%;
      top: 0px;
      left: 0;
      text-align: center;
    }

    .switch-slide .switch-label:after {
      color: #FFFFFF;
      background: #181;
      left: -100px;
    }

    .switch-slide .switch-label:before {
      background: #eceeef;
    }

    .switch-slide .switch-handle {
      display: none;
    }

    .switch-slide .switch-input:checked~.switch-label {
      background: #181;
      border-color: #0088cc;
    }

    .switch-slide .switch-input:checked~.switch-label:before {
      left: 100px;
    }

    .switch-slide .switch-input:checked~.switch-label:after {
      left: 0;
    }
  </style>
  <style>
    .banner-1x1-medium {
      width: 125px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }

    .banner-1x2-medium {
      width: 254px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }

    .banner-1x1-small {
      width: 125px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }

    .banner-1x2-small {
      width: 254px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }
  </style>
  <style>
    .scroll {
      scrollbar-color: #444 rgba(0, 0, 0, 0.3);
      scrollbar-width: thin;
      overflow-x: hidden;
      overflow-y: auto;
    }

    .scroll::-webkit-scrollbar {
      width: 10px;
      background-color: #F5F5F5;
    }

    .scroll::-webkit-scrollbar-thumb {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
      background-color: #222;
    }

    .scroll::-webkit-scrollbar-track {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
      background-color: #F5F5F5;
    }
  </style>
  <style>
    .opacity-0 {
      opacity: 0 !important;
    }

    .opacity-25 {
      opacity: .25 !important;
    }

    .opacity-50 {
      opacity: .5 !important;
    }

    .opacity-75 {
      opacity: .75 !important;
    }

    .opacity-100 {
      opacity: 1 !important;
    }

    @media (min-width: 576px) {
      .opacity-sm-0 {
        opacity: 0 !important;
      }

      .opacity-sm-25 {
        opacity: .25 !important;
      }

      .opacity-sm-50 {
        opacity: .5 !important;
      }

      .opacity-sm-75 {
        opacity: .75 !important;
      }

      .opacity-sm-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 768px) {
      .opacity-md-0 {
        opacity: 0 !important;
      }

      .opacity-md-25 {
        opacity: .25 !important;
      }

      .opacity-md-50 {
        opacity: .5 !important;
      }

      .opacity-md-75 {
        opacity: .75 !important;
      }

      .opacity-md-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 992px) {
      .opacity-lg-0 {
        opacity: 0 !important;
      }

      .opacity-lg-25 {
        opacity: .25 !important;
      }

      .opacity-lg-50 {
        opacity: .5 !important;
      }

      .opacity-lg-75 {
        opacity: .75 !important;
      }

      .opacity-lg-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 1200px) {
      .opacity-xl-0 {
        opacity: 0 !important;
      }

      .opacity-xl-25 {
        opacity: .25 !important;
      }

      .opacity-xl-50 {
        opacity: .5 !important;
      }

      .opacity-xl-75 {
        opacity: .75 !important;
      }

      .opacity-xl-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 1400px) {
      .opacity-xxl-0 {
        opacity: 0 !important;
      }

      .opacity-xxl-25 {
        opacity: .25 !important;
      }

      .opacity-xxl-50 {
        opacity: .5 !important;
      }

      .opacity-xxl-75 {
        opacity: .75 !important;
      }

      .opacity-xxl-100 {
        opacity: 1 !important;
      }
    }
  </style>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />


  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />


  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet" />
  <link href="https://animem.org/Assets/template/<?=(isset($_COOKIE["template"]))?$template[$_COOKIE["template"]]:"Superhero.min.css";?>" rel="stylesheet" />
  <link rel="stylesheet" href="https://animem.org/Assets/def.css?t=<?= time(); ?>">
</head>

<body class="bg-secondary">