<div class="card bg-dark">
  <div class="card-header border-bottom">
    <h4 class="text-center text-white"><?= $link[0]["name"]; ?></h4>
  </div>
  <div class="card-body">
    <div class="row">

      <!---------------------------------------------------------------------------->
      <div class="col-12 mb-4">
        <div class="card bg-secondary">
          <div class="card-header">
            <h6 class="text-center text-white col-12 text-truncate">Alap adatok:</h6>
          </div>
          <div class="col-12 card-body">
            <div class="row border-bottom">
              <div class="col-12">
                <span class="float-start">Facebook</span>
                <span class="float-end"><a class="caqua" href="https://facebook.com/<?= $link[0]["fb_link"]; ?>">Facebook</a></span>
              </div>
            </div>
            <div class="row border-bottom">
              <div class="col-12">
                <span class="float-start">Weboldal</span>
                <span class="float-end"><a class="caqua" href="<?= $link[0]["fan_link"]; ?>">Weboldal</a></span>
              </div>
            </div>
            <div class="row border-bottom">
              <div class="col-12">
                <span class="float-start">Indavideo</span>
                <span class="float-end"><a class="caqua" href="https://indavideo.hu/profile/<?= $link[0]["inda_link"]; ?>">Indavideo</a></span>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <span class="float-start">Email</span>
                <span class="float-end"><?= (!empty($link[0]["email"])) ? $link[0]["email"] : "Nincs megadva."; ?></span>
              </div>
            </div>
          </div>
        </div>
        <div class="card bg-secondary mt-3">
          <div class="card-header">
            <h6 class="text-center text-white col-12 text-truncate">Egyéb információk (Leírás):</h6>
          </div>
          <div class="col-12 card-body">
            <span class=""><?= $link[0]["pdes"]; ?></span>
          </div>
        </div>
        <div class="card bg-secondary mt-3">
          <div class="card-header">
            <h6 class="text-center text-white col-12 text-truncate">Statisztika:</h6>
          </div>
          <div class="col-12 card-body">
            <div class="row border-bottom">
              <div class="col-6 border-end">
                <span class="float-start">Megtekinhető videóik száma:</span>
                <span class="float-end"><?= $link[0]["savedVideo"]; ?></span>
              </div>
              <div class="col-6 border-start">
                <span class="float-start">Megtekintett videóik száma:</span>
                <span class="float-end"><?= $link[0]["viewed"]; ?></span>
              </div>
            </div>
            <div class="row border-top border-bottom">
              <div class="col-6 border-end">
                <span class="float-start">Beágyazott videóik száma:</span>
                <span class="float-end"><?= $link[0]["usedVideo"]; ?></span>
              </div>
              <div class="col-6 border-start">
                <span class="float-start">Nem beágyazott videóik száma:</span>
                <span class="float-end"><?= $link[0]["savedVideo"] - $link[0]["usedVideo"]; ?></span>
              </div>
            </div>
            <div class="row border-top">
              <div class="col-6 border-end">
                <span class="float-start">Megnyitott videóik száma:</span>
                <span class="float-end"><?= $link[0]["opened"]; ?></span>
              </div>
              <div class="col-6 border-start">
                <span class="float-start">Videóikra érkezett kattintások száma:</span>
                <span class="float-end"><?= $link[0]["clicked"]; ?></span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!---------------------------------------------------------------------------->
    </div>
  </div>
</div>