
    <div class="row mt-4">
      <div class="col-12">
        <div class="row mx-3">
          <div class="col-md-3 col-sm-12">
            <?php
            if (isset($episodeslist))
            {
            ?>
              <div class="row mb-3">
                <div class="col-12">
                  <div class="card bg-dark" id="defPlyrIsOn" style="display:block;">
                    <div class="card-header border-bottom">
                      <div class="row">
                        <div class="col-12">
                          <label class="d-grid gap-2">
                            <a class="btn btn-secondary border border-dark" href="https://animem.org/DataSheet/<?= $select["id"]; ?>">Vissza az adatlapra.</a>
                          </label>
                        </div>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          <div class="list-group scroll" style="max-height:500px;">
                            <!---------------------------------------------------------------------------->
                            <?php
                            foreach ($episodeslist as $key => $block)
                            {
                              if ($block["link_type"] != 10)
                              {
                            ?>
                                <button class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" onclick="removeActiveClass(this);loadingIframe();
                                document.getElementById('videoIframe').src='<?= $block["link"]; ?>'"><?= $block["title"]; ?></button>
                              <?php

                              }
                              else
                              {

                              ?>
                                <a class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" href="<?= $block["link"]; ?>" onclick="removeActiveClass(this);"><?= $block["title"]; ?></a>
                            <?php
                              }
                            }
                            ?>
                            <!---------------------------------------------------------------------------->
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>

                    </div>
                  </div>
                  <div class="card bg-dark" id="defPlyrIsOff" style="display:none;">
                    <div class="card-header border-bottom">
                      <h4 class="text-center text-white"></h4>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          <div class="list-group scroll" style="max-height:500px;">
                            <!---------------------------------------------------------------------------->
                            <?php
                            foreach ($episodeslist as $key => $block)
                            {
                              if ($block["link_type"] != 10)
                              {
                            ?>
                                <button class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" onclick="removeActiveClass(this);loadingIframe();
                                document.getElementById('videoIframe').src='<?= str_replace("/On/", "/Off/", $block["link"]); ?>'"><?= $block["title"]; ?></button>
                              <?php

                              }
                              else
                              {

                              ?>
                                <a class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" href="<?= $block["link"]; ?>" onclick="removeActiveClass(this)"><?= $block["title"]; ?></a>
                            <?php
                              }
                            }
                            ?>
                            <!---------------------------------------------------------------------------->
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>

                    </div>
                  </div>
                </div>
              </div>
            <?php
            }
            else
            {
            ?>
              <div class="row mb-3">
                <div class="col-12">
                  <div class="card bg-dark">
                    <div class="card-header border-bottom">
                      <h4 class="text-center text-white">Megjelenések</h4>
                    </div>
                    <div class="card-body">
                      <iframe id="cboxdiv" src="//animem.org/mininews.php" marginheight="0" marginwidth="0" scrolling="auto" allowtransparency="yes" width="100%" height="380px" frameborder="0"></iframe>
                    </div>
                    <div>
                      <script>
                        setInterval(function() {
                          document.getElementById('cboxdiv').src = '//animem.org/mininews.php';
                        }, 60000);
                      </script>
                    </div>
                  </div>
                </div>
              </div>
            <?php
            }
            ?>
            <?php
            
            if (logged() == TRUE)
            {
            ?>
              <div class="row mb-3">
                <div class="col-12">

                  <div class="card bg-dark" id="defPlyrIsOn" style="display:block;">
                    <div class="card-header border-bottom">
                      <div class="row">
                        <div class="col-12">
                          <label class="d-grid gap-2">
                            <a class="btn btn-secondary border border-dark" href="https://animem.org/Profil/<?= $_COOKIE["userID"]; ?>">Profil</a>
                          </label>
                        </div>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          <div class="list-group scroll" style="max-height:500px;">
                            <!---------------------------------------------------------------------------->

                            <!---------------------------------------------------------------------------->
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>

                    </div>
                  </div>

                </div>
              </div>
            <?php
            }
            ?>
            <div class="row mb-3">
              <div class="col-12">
                <div class="card bg-dark">
                  <div class="card-header border-bottom">
                    <h4 class="text-center text-white">Kiemelt FanSub-ok:</h4>
                  </div>
                  <div class="card-body px-2">
                    <div class="row mx-1">

                      <!---------------------------------------------------------------------------->
                      <?php
                      $counter = 0;
                      $high = json_decode(file_get_contents("Config/banner/high.json"), true);
                      foreach ($high as $key => $block)
                      {
                        $counter = ($block["size"] == "1x1") ? $counter + 1 : $counter + 2;
                      ?>
                        <div class="col-<?= (($block["size"] == "1x1") ? "4" : "8"); ?> p-1">
                          <div class="card bg-secondary">
                            <a class="<?= (($block["size"] == "1x1") ? "ratio ratio-1x1" : ""); ?>" href="<?= $block["link"]; ?>" target="_blank">
                              <img class="rounded card-img-top <?= (($block["size"] == "1x1") ? "" : "ratio ratio-1x2"); ?>" src="https://animem.org/Assets/uploads/banner/high/<?= $block["image"]; ?>" title="<?= $block["name"]; ?>" alt="<?= $block["name"]; ?>" />
                            </a>
                          </div>
                        </div>
                        <?php
                        if ($key == count($high) - 2 && $counter % 3 == 0)
                        {
                        ?>
                          <div class="col-4 p-1">
                            <div class="card bg-dark border-0">
                              <div class="ratio ratio-1x1">
                                <div class="rounded card-img-top"></div>
                              </div>
                            </div>
                          </div>
                      <?php
                        }
                      }
                      ?>
                      <!---------------------------------------------------------------------------->
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-12">
            <div class="row mb-3">
              <div class="col-12">