<div class="rapidwp-box-inside" style="margin-top:10px;">
  <header class="entry-header">
    <div class="entry-header-inside">
      <h1 class="post-title entry-title">Animem Top Lista</h1>
      <div class="rapidwp-entry-meta-single"></div>
    </div>
  </header>
  <div class="entry-content clearfix">

    <div class="container-fluid">
      <div class="row">
        <div class="col-12">

asd


        </div>
      </div>
    </div>
  </div>
  <footer class="entry-footer" style="text-align: center;">
    <!--h5>A fansub csapatok pontosabb statisztikát kaphatnak miután felvették velünk a kapcsolatott.</h5-->
    <i>- A statisztika rendszer még a tesztelés fázisban van. Ezért lehetnek hibák, késobbi változások, új adatok. -</i><br />
    <i>A statisztika rendszer 2022. 06. 20.-a óta műkődik.</i>
  </footer>
</div>