
            <!---------------------------------------------------------------------------->
            <?php
            foreach ($loop as $block)
            {
            ?>
              <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
                <a class="text-decoration-none" href="<?= BASEURL . "DataSheet" . DS . $block["ID"] . DS . str_replace(" ", "-", $block["title"]); ?>" title="<?= $block["title"]; ?>">
                  <div class="card bg-secondary" onmouseover="this.style = 'border: 1px solid var(--yellow-500)'" onmouseout="this.style = 'border: 0px'">
                    <div class="card-header">
                      <h6 class="text-center text-white col-12 text-truncate"><?= $block["title"]; ?></h6>
                    </div>
                    <img class="card-img-top" src="<?= $block["img"]; ?>" alt="<?= $block["title"]; ?>" style="height:300px!important;">
                  </div>
                </a>
              </div>
            <?php
            }
            ?>
            <!---------------------------------------------------------------------------->