</div>
</div>
</div>

<div class="col-md-3 col-sm-12">
  <div class="row mb-3">
    <div class="col-12">
      <div class="card bg-dark">
        <div class="card-header border-bottom">
          <h4 class="text-center text-white">Csatlakozz a közösséghez!</h4>
        </div>
        <div class="card-body px-2">
          <div class="row mx-2">
            <div class="col-4 p-1">
              <div class="card bg-secondary">
                <a class="ratio ratio-1x1" href="//animem.org/Discord" target="_blank">
                  <img class="rounded card-img-top" src="https://animem.org/Assets/uploads/banner/other/Discord.jpg" title="Discord" alt="Discord" />
                </a>
              </div>
            </div>
            <div class="col-4 p-1">
              <div class="card bg-secondary">
                <a class="ratio ratio-1x1" href="https://www.facebook.com/animem.org" target="_blank">
                  <img class="rounded card-img-top" src="https://animem.org/Assets/uploads/banner/other/Facebook.jpg" title="Facebook" alt="Facebook" />
                </a>
              </div>
            </div>
            <div class="col-4 p-1">
              <div class="card bg-secondary">
                <a class="ratio ratio-1x1" href="https://www.instagram.com/animem_hun/" target="_blank">
                  <img class="rounded card-img-top" src="https://animem.org/Assets/uploads/banner/other/Instagram.jpg" title="Instagram" alt="Instagram" />
                </a>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12">
      <div class="card bg-dark">
        <div class="card-header border-bottom">
          <h4 class="text-center text-white">Partnereink:</h4>
        </div>
        <div class="card-body px-2">
          <div class="row mx-1">

            <!---------------------------------------------------------------------------->
            <?php
            $counter = 0;
            $partner = json_decode(file_get_contents("Config/banner/partner.json"), true);
            foreach ($partner as $key => $block)
            {
              $counter = ($block["size"] == "1x1") ? $counter + 1 : $counter + 2;
            ?>
              <div class="col-<?= (($block["size"] == "1x1") ? "4" : "8"); ?> p-1">
                <div class="card bg-secondary">
                  <a class="<?= (($block["size"] == "1x1") ? "ratio ratio-1x1" : ""); ?>" href="<?= $block["link"]; ?>" target="_blank">
                    <img class="rounded card-img-top <?= (($block["size"] == "1x1") ? "" : "ratio ratio-1x2"); ?>" src="https://animem.org/Assets/uploads/banner/partner/<?= $block["image"]; ?>" title="<?= $block["name"]; ?>" alt="<?= $block["name"]; ?>" />
                  </a>
                </div>
              </div>
              <?php
              if ($key == count($partner) - 2 && $counter % 3 == 0)
              {
              ?>
                <div class="col-4 p-1">
                  <div class="card bg-dark border-0">
                    <div class="ratio ratio-1x1">
                      <div class="rounded card-img-top"></div>
                    </div>
                  </div>
                </div>
            <?php
              }
            }
            ?>
            <!---------------------------------------------------------------------------->
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12">
      <div class="card bg-dark">
        <div class="card-header border-bottom">
          <h4 class="text-center text-white">Kiemelt FanSub-ok:</h4>
        </div>
        <div class="card-body px-2">
          <div class="row mx-1">

            <!---------------------------------------------------------------------------->
            <?php
            $counter = 0;
            $high = json_decode(file_get_contents("Config/banner/high.json"), true);
            foreach ($high as $key => $block)
            {
              $counter = ($block["size"] == "1x1") ? $counter + 1 : $counter + 2;
            ?>
              <div class="col-<?= (($block["size"] == "1x1") ? "4" : "8"); ?> p-1">
                <div class="card bg-secondary">
                  <a class="<?= (($block["size"] == "1x1") ? "ratio ratio-1x1" : ""); ?>" href="<?= $block["link"]; ?>" target="_blank">
                    <img class="rounded card-img-top <?= (($block["size"] == "1x1") ? "" : "ratio ratio-1x2"); ?>" src="https://animem.org/Assets/uploads/banner/high/<?= $block["image"]; ?>" title="<?= $block["name"]; ?>" alt="<?= $block["name"]; ?>" />
                  </a>
                </div>
              </div>
              <?php
              if ($key == count($high) - 2 && $counter % 3 == 0)
              {
              ?>
                <div class="col-4 p-1">
                  <div class="card bg-dark border-0">
                    <div class="ratio ratio-1x1">
                      <div class="rounded card-img-top"></div>
                    </div>
                  </div>
                </div>
            <?php
              }
            }
            ?>
            <!---------------------------------------------------------------------------->
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>

<div class="row mx-3 mb-3">
  <div class="col-12 px-3">
    <p style="vertical-align:top;text-align:center;width:99%;display: inline-block;">
      <?php
      $diff = date_diff(date_create("2009-10-23"), date_create(date("Y-m-d")));

      echo "Már " . $diff->y . " éve, " . $diff->m . " hónapja és " . $diff->d . " napja csak értetek.";

      ?><br /><i id="demo"></i>
      <br />
      Mai Látogatók: <span><?php echo $visits_today_unreg; ?></span><br />
      Az elmult 30 percben online Látogatók: <span id=""><?php echo onlineUsers($conn); ?></span>
    </p>
  </div>
</div>
</div>

<script>
  function Copy() {
    let textarea = document.getElementById("jsonzx126");
    let div = document.getElementById("jsonzx124");
    textarea = textarea.outerHTML;
    textarea = textarea.replace(' id="jsonzx126"', '');
    if (typeof document.getElementById("copybox") === 'undefined' || document.getElementById("copybox") === null) {
      div.innerHTML += '<textarea id="copybox">' + textarea + '</textarea>';
    } else {
      document.getElementById("copybox").innerHTML = textarea;
    }
    let copyTextarea = document.getElementById("copybox");
    copyTextarea.style = "display: block;"; //select the text area
    copyTextarea.select(); //select the text area
    copyTextarea.setSelectionRange(0, 99999);
    document.execCommand("copy"); //copy to clipboard
    /* Alert the copied text */
    alert("Copied the text: \n" + copyTextarea.value);
    copyTextarea.style = "display: none;"; //select the text area
  }

  function myFunction2() {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
      x.className += " responsive";
    } else {
      x.className = "topnav";
    }
  }
  // Set the date we're counting down to
  var countDownDate = new Date("Sep 18, 2022 00:00:00").getTime();
  // Update the count down every 1 second
  var x = setInterval(function() {
    // Get today's date and time
    var now = new Date().getTime();
    // Find the distance between now and the count down date
    var distance = countDownDate - now;
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    // Display the result in the element with id="demo"
    document.getElementById("demo").innerHTML = days + " Nap " + hours + " Óra " + minutes + " Perc " + seconds + " Másodperc és Hellmesternek születés napja lesz!";
    // If the count down is finished, write some text
    if (distance < 0) {
      clearInterval(x);
      document.getElementById("demo").innerHTML = "EXPIRED";
    }
  }, 1000);

  function jsonzx102() {
    document.getElementById("jsonzx126").style.display = 'none';
    document.getElementById("jsonzx116").style.display = 'block';
    document.getElementById("jsonzx126").addEventListener("load", function(e) {
      // alert(this.nodeName);
      document.getElementById("jsonzx126").style.display = 'block';
      document.getElementById("jsonzx116").style.display = 'none';
      console.log(e.target);
    });
  }

  function GEBI(X) {
    return document.getElementById(X);
  }

  function jsonzx100() {
    loadingIframe();
    jsonzx123();
    jsonzx122();
  }

  function jsonzx120(str) // counter
  {
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        console.log(this.responseText);
        document.getElementById("jsonzx128").innerHTML = "Megtekintette " + this.responseText + " ember.";
      }
    }
    xmlhttp.open("GET", "https://animem.org/counter.php?q=" + str, true);
    xmlhttp.send();
  }

  function jsonzx119(str) // counter
  {
    if (typeof animedata === 'undefined' || animedata === null) {
      console.log("Nincs animedata.");
    } else {
      animedata["links"] = jsonzx125;
      console.log("Van animedata.");
      let xmlhttp = new XMLHttpRequest();
      xmlhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
          console.log(this.responseText);
          //  let jsonData = JSON.parse(this.responseText);
        }
      };
      console.log('https://x.animem.org/DataSheet/saver/?q=' + JSON.stringify(animedata));
      xmlhttp.open('GET', 'https://x.animem.org/DataSheet/saver/?q=' + JSON.stringify(animedata), true);
      xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
      xmlhttp.send();
    }
  }

  function jsonzx123() {
    //json125
    if (typeof jsonzx125 === 'undefined' || jsonzx125 === null) {
      // variable is undefined or null
    } else {
      let html = "<div>",
        plyr = "",
        noplyr = "",
        div = document.getElementById('jsonzx124'),
        bool = 'false',
        okey = "",
        ovalue = "",
        link = "";
      html = '<div id="icipiciriczropic">';
      for (let key in jsonzx125) {
        link = tikitaki[key];
        let value = jsonzx125[key];
        value = value.replace('https://', '//');
        value = value.replace('http://', '//');
        value = value.replace('//mega.nz/file', '//mega.nz/embed');
        let strCount = 0;
        let strType = 0;
        value = value.replace('//Semmi', '');
        value = value.replace('//embed.animem.org/Video/EmbedOta/', '//embed.animem.org/');
        value = value.replace('//embed.animem.org/', '//embed.animem.org/Video/EmbedOta/');
        value = value.replace('//embed.indavideo.hu/player/video/', '//embed.animem.org/Video/EmbedInda/');
        value = value.replace('//indavideo.hu/video/', '//embed.animem.org/Video/Inda/');

        console.log("<++ START ++>");
        strCount = value.length;
        console.log("strCount:" + strCount);
        value = value.replace('On/', '');
        console.log("value.length:" + value.length);
        if (value.length < strCount) {
          strType = 1;
          console.log("strType: 1");
        } else {
          value = value.replace('Off/', '');
          console.log("value.length:" + value.length);
          if (value.length < strCount) {
            strType = 2;
            console.log("strType: 1");
          } else {
            value = value.replace('Null/', '');
            console.log("value.length:" + value.length);
            if (value.length < strCount) {
              strType = 3;
              console.log("strType: 1");
            } else {
              strType = 1;
              console.log("strType: 1");
            }
          }
        }


        if (strType == 1) {
          value = value.replace('//embed.animem.org/Video/EmbedOta/', '//embed.animem.org/Video/EmbedOta/On/');
          value = value.replace('//embed.animem.org/Video/EmbedInda/', '//embed.animem.org/Video/EmbedInda/On/');
          value = value.replace('//embed.animem.org/Video/Inda/', '//embed.animem.org/Video/Inda/On/');
        }



        if (strType == 2) {
          value = value.replace('//embed.animem.org/Video/EmbedOta/', '//embed.animem.org/Video/EmbedOta/Off/');
          value = value.replace('//embed.animem.org/Video/EmbedInda/', '//embed.animem.org/Video/EmbedInda/Off/');
          value = value.replace('//embed.animem.org/Video/Inda/', '//embed.animem.org/Video/Inda/Off/');
        }

        if (strType == 3) {
          value = value.replace('//embed.animem.org/Video/EmbedOta/', '//embed.animem.org/Video/EmbedOta/Null/');
          value = value.replace('//embed.animem.org/Video/EmbedInda/', '//embed.animem.org/Video/EmbedInda/Null/');
          value = value.replace('//embed.animem.org/Video/Inda/', '//embed.animem.org/Video/Inda/Null/');
        }
        console.log("<++ END ++>");
        /*
         */





        value = value.replace('.mp4?', '/');
        if (bool == 'false') {
          bool = 'true';
          okey = key;
          ovalue = value;
        }
        html = html + '<button onclick="document.getElementById(\'jsonzx127\').innerHTML = \'';
        html = html + key;
        html = html + '\';jsonzx102();jsonzx120(\'' + link + '\');jsonzx119(\'' + link + '\');document.getElementById(\'jsonzx126\').src=\'';
        html = html + value;
        html = html + '\'" style="width: 25%; padding:10px 0;">';
        html = html + key;
        html = html + '</button>';
        noplyr += '<button onclick="document.getElementById(\'jsonzx127\').innerHTML = \'';
        noplyr += key;
        noplyr += '\';jsonzx102();jsonzx120(\'' + link + '\');jsonzx119(\'' + link + '\');document.getElementById(\'jsonzx126\').src=\'';
        noplyr += value.replace('/On/', '/Off/');
        noplyr += '\'" style="width: 25%; padding:10px 0;">';
        noplyr += key;
        noplyr += '</button>';
        // new script
        /*
   
   
   
   
   
                     link = jsonzx125[key];
   
                     let value = jsonzx125[key];
   
                     value = '//embed.animem.org/Embed/' + value;
   
                     if(key != "_type")
   
                     {
   
                     if (bool == 'false') {
   
                         bool = 'true';
   
                         okey = key;
   
                         ovalue = value;
   
                     }
   
                     html = html + '<button onclick="document.getElementById(\'jsonzx127\').innerHTML = \'';
   
                     html = html + key;
   
                     html = html + '\';jsonzx102();jsonzx120(\'' + link + '\');jsonzx119(\'' + link + '\');document.getElementById(\'jsonzx126\').src=\'';
   
                     html = html + value;
   
                     html = html + '\'" style="width: 25%; padding:10px 0;">';
   
                     html = html + key;
   
                     html = html + '</button>';
   
   
   
   
   
   
   
                     noplyr += '<button onclick="document.getElementById(\'jsonzx127\').innerHTML = \'';
   
                     noplyr += key;
   
                     noplyr += '\';jsonzx102();jsonzx120(\'' + link + '\');jsonzx119(\'' + link + '\');document.getElementById(\'jsonzx126\').src=\'';
   
                     noplyr += value.replace('/On/', '/Off/');
   
                     noplyr += '\'" style="width: 25%; padding:10px 0;">';
   
                     noplyr += key;
   
                     noplyr += '</button>';
   
                     }
   
   
   
   
   
          */
        //console.log(key, value);
      }
      html = html + '</div>';
      html = html + '<div id="iciripiciririczropicegyiciripiciririczropoiccalropizott">';
      html = html + noplyr;
      html = html + '</div>';
      html = html + '</div>';
      html = html + '<h6 id="jsonzx127" style="text-aligh: center; width: 100%;' + ' border: 1px solid #171717;' + ' background: #333;' + ' color: #fff;' + ' text-align: center;' + ' padding: 10px 0;' + ' font-size: 12px;">';
      html = html + okey;
      html = html + '</h6>';
      /*
      html = html + '<button id="jsonzx128" style="text-aligh: center; width: 50%;' + ' border: 1px solid #171717;' + ' background: #333;' + ' color: #fff;' + ' text-align: center;' + ' padding: 10px 0;' + ' font-size: 16px;">';
      html = html + "Megtekintette 0 ember.";
      html = html + '</button>';
      html = html + '<button id="jsonzx129" style="text-aligh: center; width: 50%;' + ' border: 1px solid #171717;' + ' background: #333;' + ' color: #fff;' + ' text-align: center;' + ' padding: 10px 0;' + ' font-size: 16px;">';
      html = html + "A forditás készítője: Ismeretlen";
      html = html + '</button><hr />';
      */
      html = html + '<div class="row mx-0" style="">';
      html = html + '<iframe id="jsonzx126" allowfullscreen src="';
      html = html + ovalue;
      html = html + '" scrolling="no" style="width: 100%;min-height: 486px;"  frameborder="0"></iframe>';
      html = html + '<iframe id="jsonzx116" allowfullscreen src="https://animem.org/loader.html" scrolling="no" style="width: 100%;min-height: 486px; display:none;"  frameborder="0"></iframe>';
      html = html + '</div>';
      html = html + '<label class="switch switch-slide" style="text-aligh: center; width: 50%;' + ' text-align: center;' + ' padding: 0px 0;' + ' margin-top: 0px;' + ' font-size: 12px;position: relative;display: inline-block;vertical-align: middle;">';
      html = html + '<input class="switch-input" type="checkbox" checked id="piciricz" onclick="riczropic()"/>';
      html = html + '<span class="switch-label" data-on="Plyr Be" data-off="Plyr Ki"></span>';
      html = html + '<span class="switch-handle"></span>';
      html = html + '</label>';
      html = html + '<label style="text-aligh: center; width: 50%;' + ' border: 1px solid #171717;' + ' background: #333;' + ' color: #fff;' + ' text-align: center;' + ' padding: 0px 10px;' + ' margin-top: 0px;' + ' font-size: 12px;position: relative;display: inline-block;vertical-align: middle;">';
      html = html + '<span onclick="Copy();">Embed másolása</span></label>';
      div.innerHTML = html;
      jsonzx120(link);
      jsonzx119(link);
    }
  }

  function riczropic() {
    var checkBox = GEBI("piciricz");
    var icipiciriczropic = GEBI("icipiciriczropic");
    var iciripiciririczropicegyiciripiciririczropoiccalropizott = GEBI("iciripiciririczropicegyiciripiciririczropoiccalropizott");
    if (checkBox.checked == true) {
      jsonzx102(GEBI("jsonzx126").src.replace('/Off/', '/On/'));
      GEBI("jsonzx126").src = GEBI("jsonzx126").src.replace('/Off/', '/On/');
      iciripiciririczropicegyiciripiciririczropoiccalropizott.style.display = "none";
      icipiciriczropic.style.display = "block";
    } else {
      jsonzx102(GEBI("jsonzx126").src.replace('/On/', '/Off/'));
      GEBI("jsonzx126").src = GEBI("jsonzx126").src.replace('/On/', '/Off/');
      iciripiciririczropicegyiciripiciririczropoiccalropizott.style.display = "block";
      icipiciriczropic.style.display = "none";
    }
  }



  function loadingIframe() {
    document.getElementById("videoIframe").style.display = 'none';
    document.getElementById("loadingIframe").style.display = 'block';
    document.getElementById("videoIframe").addEventListener("load", function(e) {
      // alert(this.nodeName);
      document.getElementById("videoIframe").style.display = 'block';
      document.getElementById("loadingIframe").style.display = 'none';
      //console.log(e.target);
    });
  }

  function SwitchPlyr() {
    if (GEBI("SwitchPlyr").checked == true) {
      loadingIframe();
      GEBI("videoIframe").src = GEBI("videoIframe").src.replace('/Off/', '/On/');
      GEBI("defPlyrIsOn").style.display = "block";
      GEBI("defPlyrIsOff").style.display = "none";
      GEBI("SwitchPlyrButton").innerHTML = "Plyr Be";
      GEBI("SwitchPlyrButton").classList.toggle('btn-success');
      GEBI("SwitchPlyrButton").classList.toggle('btn-secondary');
    } else {
      loadingIframe();
      GEBI("videoIframe").src = GEBI("videoIframe").src.replace('/On/', '/Off/');
      GEBI("defPlyrIsOn").style.display = "none";
      GEBI("defPlyrIsOff").style.display = "block";
      GEBI("SwitchPlyrButton").innerHTML = "Plyr Ki";
      GEBI("SwitchPlyrButton").classList.toggle('btn-success');
      GEBI("SwitchPlyrButton").classList.toggle('btn-secondary');
    }
  }

  function CopyIframe() {
    let textarea = GEBI("videoIframe");
    let div = GEBI("jsonzx124");
    textarea = textarea.outerHTML;
    textarea = textarea.replace(' id="videoIframe"', '');
    if (typeof GEBI("copybox") === 'undefined' || GEBI("copybox") === null) {
      div.innerHTML += '<textarea id="copybox">' + textarea + '</textarea>';
    } else {
      GEBI("copybox").innerHTML = textarea;
    }
    let copyTextarea = GEBI("copybox");
    copyTextarea.style = "display: block;"; //select the text area
    copyTextarea.select(); //select the text area
    copyTextarea.setSelectionRange(0, 99999);
    document.execCommand("copy"); //copy to clipboard
    /* Alert the copied text */
    alert("Copied the text: \n" + copyTextarea.value);
    copyTextarea.style = "display: none;"; //select the text area
  }


  function removeActiveClass(e) {

    let elements = e.parentNode.getElementsByClassName('active');
    while (elements.length > 0) {
        elements[0].classList.remove('active');
    }
      e.classList.add('active');
    }

  





  function jsonzx122() {
    let html = '',
      htmlstart = '' + '<div id="mxzalert">' + '<div>' + '<div class="modal-content">' + '<div class="modal-header">' + '<h4 class="modal-title">Figyelem!</h4>' + ' </div>' + '<div class="modal-body">' + '   <p>',
      htmlend = '' + '</p>' + '</div>' + '<div class="modal-footer">' + ' <button type="button" onclick="document.getElementById(\'jsonzx124\').style.display = \'block\'; document.getElementById(\'mxzalert\').style.display = \'none\';">OKÉ</button>' + ' </div>' + ' </div>' + '</div>' + '</div>',
      divR17 = document.getElementById('divR17'),
      divRX = document.getElementById('divRX'),
      divRP = document.getElementById('divRP'),
      R17 = '' + 'A következő tartalom kiskorúak számára káros lehet. <br />' + 'Az alábbi animét csak 18. életévét betöltött személyeknek ajánljuk!<br />' + 'Az anime \'R-17+\' beorolású az-az tartalmazhat erőszakot és trágár beszédet!',
      RP = '' + 'A következő tartalom kiskorúak számára káros lehet. <br />' + 'Az alábbi animét csak 18. életévét betöltött személyeknek ajánljuk!<br />' + 'Az anime \'R+\' beorolású az-az tartalmazhat "Enyhe meztelenséget", illetve erőszakot és trágár beszédet!',
      RX = '' + 'A következő tartalom kiskorúak számára káros lehet. <br />' + 'Az alábbi animét csak 18. életévét betöltött személyeknek ajánljuk!<br />' + 'Az anime \'Rx\' beorolású az-az tartalmaz Hentai-t (extrém szexuális tartalom / meztelenség)!';
    if (typeof divR17 !== 'undefined' && divR17 !== null) {
      console.log('divR17');
      divR17.innerHTML = htmlstart + R17 + htmlend
      document.getElementById('jsonzx124').style.display = 'none';
    } else if (typeof divRX !== 'undefined' && divRX !== null) {
      console.log('divRX');
      divRX.innerHTML = htmlstart + RX + htmlend
      document.getElementById('jsonzx124').style.display = 'none';
    } else if (typeof divRP !== 'undefined' && divRP !== null) {
      console.log('divRP');
      divRP.innerHTML = htmlstart + RP + htmlend
      document.getElementById('jsonzx124').style.display = 'none';
    } else {}
  }
  /*
    function fansubajax() {
      let fansubtablezz17 = document.getElementById('fansubtablezz17');
      if (typeof fansubtablezz17 !== 'undefined' && fansubtablezz17 !== null) {
        console.log('I\'m run!');
        let name = document.getElementById('fanname'),
          fb = document.getElementById('facebook'),
          inda = document.getElementById('indavideo'),
          fan_link = document.getElementById('website');
          videonum = document.getElementById('videonum');
        let xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            console.log(this.responseText);
            let jsonData = JSON.parse(this.responseText);
            console.log('Invalid Credentials!');

            fb.href = 'https://facebook.com/' + jsonData.fb_link;
            if (jsonData.fb_link != '#') fb.innerHTML = '<span style="color:#409bd4;">Facebook</span>';
            else fb.innerHTML = '<span style="color:red;">Facebook</span>';

            inda.href = 'https://indavideo.hu/profile/' + jsonData.inda_link;
            if (jsonData.inda_link != '#') inda.innerHTML = '<span style="color:#409bd4;">Indavideo</span>';
            else inda.innerHTML = '<span style="color:red;">Indavideo</span>';

            fan_link.href = jsonData.fan_link;
            if (jsonData.fan_link != '#') fan_link.innerHTML = '<span style="color:#409bd4;">Weboldal</span>';
            else fan_link.innerHTML = '<span style="color:red;">Weboldal</span>';

            if (jsonData.videonum != '0') 
            videonum.innerHTML = '<span style="color:#409bd4;">' + jsonData.videonum + '</span>';

            name.innerHTML = jsonData.name;
          }
        };
        xmlhttp.open('GET', 'https://animem.org/api.php?id=' + window.location.search.substr(1), true);
        xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        xmlhttp.send();
      }
    }

    */
  window.onload = jsonzx100();
</script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>