
<div class="rapidwp-box-inside" style="margin-top:10px;">
  <header class="entry-header">
    <?php if (is_array($arr2))
    { ?>
      <div class="entry-header-inside" style="text-align:left; vertical-align:middle;display: table-cell;">

        <button style="padding: 7.2px 12px;">
          <a style="margin: 7.2px 12px; width:100%;" href="https://animem.org/<?= $arr2[0]["link"]; ?>" rel="bookmark">Vissza a Széria oldalára.</a>
        </button>
      </div>
    <?php } ?>
    <div class="entry-header-inside" style="text-align:inherit; vertical-align:middle;display: table-cell;">
      <span class="post-title entry-title" style="vertical-align:center">
        <a href="https://animem.org/<?= $select["link"]; ?>" rel="bookmark"><?= $select["title"]; ?></a>
      </span>
    </div>
  </header>
  <div class="entry-content">
    <div>
      <div style="width:100%; float:left;">
        <div>
          <div></div>
        </div>
        <div>
          <table style="border:0px;">
            <tr>
              <td style="vertical-align: top; text-align: center; width: 33%; background-color: #212121;border:0px;">
                <img src="<?= $select["anime"]["img"]; ?>" sizes="(max-width: 225px) 100vw, 225px" height="320" />
              </td>
              <td style="vertical-align:top;text-align:left; width:66%; border:0px; padding-right:0;">
                <div>
                  <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                    <span style="vertical-align:top;text-align:left;">angol cím:</span>
                    <span style="float:right;"><?= htmlspecialchars_decode($select["anime"]["english"]); ?></span>
                  </div>
                </div>
                <div>
                  <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                    <span style="vertical-align:top;text-align:left;">egyéb cím(ek):</span>
                    <span style="float:right;"><?= htmlspecialchars_decode($select["anime"]["synonyms"]); ?></span>
                  </div>
                </div>
                <div>
                  <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                    <span style="vertical-align:top;text-align:left;">japán cím:</span>
                    <span style="float:right;"><?= htmlspecialchars_decode($select["anime"]["japanese"]); ?></span>
                  </div>
                </div>
                <div>
                  <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                    <span style="vertical-align:top;text-align:left;">részek összesen:</span>
                    <span style="float:right;"><?= $select["anime"]["episodes"]; ?> rész</span>
                  </div>
                </div>
                <div>
                  <?php if (!empty($select["anime"]["cycle"]))
                  { ?>
                    <?php foreach ($select["anime"]["cycle"] as $key => $value)
                    {
                      $i = 0; ?>
                      <div>
                        <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                          <span style="vertical-align:top;text-align:left;">
                            <?= str_replace(array_keys($cycle), $cycle, $key); ?>
                          </span>
                          <span style="float:right;">

                            <?php $i = 0;
                            foreach ($value as $key1 => $value1)
                            {
                              $i++;
                              echo $value1["name"];
                              echo ($i < count($value)) ? ", " : "";
                            } ?>
                          </span>
                        </div>
                      <?php } ?>

                    <?php }
                  else
                  { ?>
                    <?php } ?>
                    <div>
                      <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">myanimelist:</span>
                        <span style="float:right;">[<a href="<?= $select["anime"]["link"]; ?>" target="_blank" class="bluuuu">link</a>]</span>
                      </div>
                    </div>
                    <div>
                      <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">szezon:</span>
                        <span style="float:right;"><?= $select["anime"]["year"]; ?> - <?= $select["anime"]["season"]; ?></span>
                      </div>
                    </div>
                    <div>
                      <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">típus:</span>
                        <span style="float:right;"><?= $select["anime"]["type"]; ?></span>
                      </div>
                    </div>
                    <div>
                      <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">age rating:</span>
                        <span style="float:right;"><?= $select["anime"]["age_rating"]; ?></span>
                      </div>
                    </div>
                    <div>
                      <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">forrás:</span>
                        <span style="float:right;"><?= $select["anime"]["source"]; ?></span>
                      </div>
                    </div>
                    <div>
                      <div style="vertical-align:top;text-align:left;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">forditotta:</span>
                        <span style="float:right;"><?= $select["uploaders"]; ?></span>
                      </div>
                    </div>
                      </div>
              </td>
            </tr>
            <tr style=" background-color: #212121;">
              <td style="border:0px; height:5px; background-color: #212121;"></td>
            </tr>
            <tr style="">
              <td colspan="3" style="border:0px;">
                <div>
                  <h4>leirás:</h4>
                </div>
                <hr />
                <div>
                  <p><?= htmlspecialchars_decode($select["description"]); ?></p>
                </div>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div style="padding: 15px;"><?= $select["episodelist"]; ?>
      </div>
    </div>
  </div>
  <footer class="entry-footer" style="border-top:1px solid white;"></footer>
</div>

