<div class="rapidwp-box-inside" style="margin-top:10px;">
  <header class="entry-header">
    <div>
      <div class="entry-header-inside" style="text-align:left; vertical-align:middle;display: table-cell;">
        <button style="padding: 7.2px 12px;">
          <a style="margin: 7.2px 12px; width:100%;" href="{{DATASHEET}}" rel="bookmark">Vissza az adatlapra.</a>
        </button>
      </div>
      <div class="entry-header-inside" style="text-align:inherit; vertical-align:middle;display: table-cell;">
        <span class="entry-title" style="vertical-align:center; color : white;">
          {{TITLE}}
        </span>
      </div>
    </div>
    <div class="rapidwp-entry-meta-single"></div>
  </header>
  <div class="entry-content clearfix">
    {{CONTENT}}
  </div>
  <footer class="entry-footer"></footer>
</div>