<!DOCTYPE html>
<html lang="hu">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Animem | <?= $title; ?>">
  <meta property="og:image" content="https://animem.org/Assets/uploads/fontos_kepek/FaceBanner5.jpg">

  <meta name="description" content="Animem.org az animék országa. Az animék országában szinte bármilyen animét megtalálhatsz. Legyen az szinkronos vagy feliratos. Mindezt a lehető legjobb minőségben.">
  <meta name="keywords" content="www.animem.org,animem.org,animem,anime,anime magyar,anime magyar felirattal,magyar felirat,magyarul,magyar,anime felirat,anime felirattal, anime, manga, magyar, fansub, felirat, videó, online, <?= $title; ?>">
  <meta name="robots" content="index,follow">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta property="og:url" content="https://animem.org/">
  <meta property="og:type" content="article">
  <meta property="og:title" content="Animem | <?= $title; ?> - Magyar Felirattal">
  <meta property="og:description" content="Animem.org az animék országa. Az animék országában szinte bármilyen animét megtalálhatsz. Legyen az szinkronos vagy feliratos. Mindezt a lehető legjobb minőségben.">

  <link rel="icon" href="https://animem.org/Assets/uploads/fontos_kepek/32.jpg" sizes="32x32">
  <link rel="icon" href="https://animem.org/Assets/uploads/fontos_kepek/192.jpg" sizes="192x192">
  <link rel="apple-touch-icon" href="https://animem.org/Assets/uploads/fontos_kepek/180.jpg">

  <title>Animem | <?= $title; ?></title>

  <?php
  $image = ((time() % 2) == 0) ? "https://animem.org/Assets/uploads/fontos_kepek/background.jpg" : "https://animem.org/Assets/uploads/fontos_kepek/background2.jpg";
  ?>



  <script type="text/javascript" src="https://animem.org/Assets/jquery/jquery.min.js" id="jquery-core-js"></script>
  <script type="text/javascript" src="https://animem.org/Assets/jquery/jquery-migrate.min.js" id="jquery-migrate-js"></script>






  <style>
    .switch {
      position: relative;
      display: inline-block;
      vertical-align: top;
      width: 100px;
      height: 20px;
      padding: 3px;
      margin: 0 5px 5px 0;
      background: linear-gradient(to bottom, #eeeeee, #FFFFFF 25px);
      background-image: -webkit-linear-gradient(top, #eeeeee, #FFFFFF 25px);
      border-radius: 18px;
      box-shadow: inset 0 -1px white, inset 0 1px 1px rgba(0, 0, 0, 0.05);
      cursor: pointer;
      box-sizing: content-box;
    }

    .switch-input {
      position: absolute;
      top: 0;
      left: 0;
      opacity: 0;
      box-sizing: content-box;
    }

    .switch-label {
      position: relative;
      display: block;
      height: inherit;
      font-size: 12px;
      background: #eceeef;
      border-radius: inherit;
      box-sizing: content-box;
    }

    .switch-label:before,
    .switch-label:after {
      position: absolute;
      top: 50%;
      -webkit-transition: inherit;
      -moz-transition: inherit;
      -o-transition: inherit;
      transition: inherit;
      box-sizing: content-box;
    }

    .switch-label:before {
      content: attr(data-off);
      right: 11px;
      color: #523e3e;
    }

    .switch-label:after {
      content: attr(data-on);
      left: 11px;
      color: #FFFFFF;
      opacity: 0;
    }

    .switch-input:checked~.switch-label {
      background: #E1B42B;
    }

    .switch-input:checked~.switch-label:before {
      opacity: 0;
    }

    .switch-input:checked~.switch-label:after {
      opacity: 1;
    }

    .switch-handle {
      position: absolute;
      top: 4px;
      left: 4px;
      width: 28px;
      height: 28px;
      background: linear-gradient(to bottom, #FFFFFF 40%, #f0f0f0);
      background-image: -webkit-linear-gradient(top, #FFFFFF 40%, #f0f0f0);
      border-radius: 100%;
    }

    .switch-handle:before {
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -6px 0 0 -6px;
      width: 12px;
      height: 12px;
      background: linear-gradient(to bottom, #eeeeee, #FFFFFF);
      background-image: -webkit-linear-gradient(top, #eeeeee, #FFFFFF);
      border-radius: 6px;
    }

    .switch-input:checked~.switch-handle {
      left: 74px;
    }

    /* Transition
    ========================== */
    .switch-label,
    .switch-handle {
      transition: All 0.3s ease;
      -webkit-transition: All 0.3s ease;
      -moz-transition: All 0.3s ease;
      -o-transition: All 0.3s ease;
    }

    /* Sw itch Slide
    ==========================*/
    .switch-slide {
      padding: 0;
      margin: 5px 0 0;
      background: #eceeef;
      border-radius: 0;
      background-image: none;
    }

    .switch-slide .switch-label {
      box-shadow: none;
      background: none;
      overflow: hidden;
    }

    .switch-slide .switch-label:after,
    .switch-slide .switch-label:before {
      width: 100%;
      height: 65%;
      top: 0px;
      left: 0;
      text-align: center;
    }

    .switch-slide .switch-label:after {
      color: #FFFFFF;
      background: #181;
      left: -100px;
    }

    .switch-slide .switch-label:before {
      background: #eceeef;
    }

    .switch-slide .switch-handle {
      display: none;
    }

    .switch-slide .switch-input:checked~.switch-label {
      background: #181;
      border-color: #0088cc;
    }

    .switch-slide .switch-input:checked~.switch-label:before {
      left: 100px;
    }

    .switch-slide .switch-input:checked~.switch-label:after {
      left: 0;
    }
  </style>
  <style>
    .banner-1x1-medium {
      width: 125px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }

    .banner-1x2-medium {
      width: 254px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }

    .banner-1x1-small {
      width: 125px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }

    .banner-1x2-small {
      width: 254px;
      height: 125px;
      padding: 0px;
      margin: 0px;
      border-radius: 5px;
      border: solid 1px black;
      background-color: #d3d3d32e;
    }
  </style>
  <style>
    .scroll {
      scrollbar-color: #444 rgba(0, 0, 0, 0.3);
      scrollbar-width: thin;
      overflow-x: hidden;
      overflow-y: auto;
    }

    .scroll::-webkit-scrollbar {
      width: 10px;
      background-color: #F5F5F5;
    }

    .scroll::-webkit-scrollbar-thumb {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
      background-color: #222;
    }

    .scroll::-webkit-scrollbar-track {
      -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
      background-color: #F5F5F5;
    }
  </style>
  <style>
    .opacity-0 {
      opacity: 0 !important;
    }

    .opacity-25 {
      opacity: .25 !important;
    }

    .opacity-50 {
      opacity: .5 !important;
    }

    .opacity-75 {
      opacity: .75 !important;
    }

    .opacity-100 {
      opacity: 1 !important;
    }

    @media (min-width: 576px) {
      .opacity-sm-0 {
        opacity: 0 !important;
      }

      .opacity-sm-25 {
        opacity: .25 !important;
      }

      .opacity-sm-50 {
        opacity: .5 !important;
      }

      .opacity-sm-75 {
        opacity: .75 !important;
      }

      .opacity-sm-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 768px) {
      .opacity-md-0 {
        opacity: 0 !important;
      }

      .opacity-md-25 {
        opacity: .25 !important;
      }

      .opacity-md-50 {
        opacity: .5 !important;
      }

      .opacity-md-75 {
        opacity: .75 !important;
      }

      .opacity-md-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 992px) {
      .opacity-lg-0 {
        opacity: 0 !important;
      }

      .opacity-lg-25 {
        opacity: .25 !important;
      }

      .opacity-lg-50 {
        opacity: .5 !important;
      }

      .opacity-lg-75 {
        opacity: .75 !important;
      }

      .opacity-lg-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 1200px) {
      .opacity-xl-0 {
        opacity: 0 !important;
      }

      .opacity-xl-25 {
        opacity: .25 !important;
      }

      .opacity-xl-50 {
        opacity: .5 !important;
      }

      .opacity-xl-75 {
        opacity: .75 !important;
      }

      .opacity-xl-100 {
        opacity: 1 !important;
      }
    }

    @media (min-width: 1400px) {
      .opacity-xxl-0 {
        opacity: 0 !important;
      }

      .opacity-xxl-25 {
        opacity: .25 !important;
      }

      .opacity-xxl-50 {
        opacity: .5 !important;
      }

      .opacity-xxl-75 {
        opacity: .75 !important;
      }

      .opacity-xxl-100 {
        opacity: 1 !important;
      }
    }
  </style>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />


  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />


  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet" />
  <link href="https://animem.org/Assets/template/<?= (isset($_COOKIE["template"])) ? $template[$_COOKIE["template"]] : "Superhero.min.css"; ?>" rel="stylesheet" />

</head>

<body class="bg-secondary">
  <div class="container-fluid mt-3">
    <div class="row">
      <div class="col-12">
        <a href="https://animem.org/" rel="home">
          <img src="https://animem.org/Assets/uploads/fontos_kepek/header.jpg" alt="" class="px-3" width="100%" height="250px">
        </a>
      </div>
    </div>
    <div class="row mb-4">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mx-3 px-3">
          <a class="navbar-brand" href="https://animem.org/Home">Kezdőlap</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0">
              <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="https://www.twitch.tv/valorzoner">Driday-Fanzay</a></li>
              <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="https://animem.org/Anime/">Animék A-Z</a></li>
              <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="https://animem.org/statistic/">Statisztika</a></li>
              <li class="nav-item"><a class="nav-link fs-6" aria-current="page" href="https://animem.org/Seasonal/">Szezonális</a></li>
            </ul>
            <form action="/" method="GET" class="d-flex">
              <input class="form-control me-2" name="s" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </nav>







      </div>
    </div>
    <div class="row mt-4">
      <div class="col-12">
        <div class="row mx-3">
          <div class="col-md-3 col-sm-12">
            <?php
            if (isset($episodeslist))
            {
            ?>
              <div class="row mb-3">
                <div class="col-12">
                  <div class="card bg-dark" id="defPlyrIsOn" style="display:block;">
                    <div class="card-header border-bottom">
                      <div class="row">
                        <div class="col-12">
                          <label class="d-grid gap-2">
                            <a class="btn btn-secondary border border-dark" href="https://animem.org/DataSheet/<?= $select["id"]; ?>" target="_blank">Vissza az adatlapra.</a>
                          </label>
                        </div>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          <div class="list-group scroll" style="max-height:500px;">
                            <!---------------------------------------------------------------------------->
                            <?php
                            foreach ($episodeslist as $key => $block)
                            {
                              if ($block["link_type"] != 10)
                              {
                            ?>
                                <button class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" onclick="removeActiveClass(this);loadingIframe();
                                document.getElementById('videoIframe').src='<?= $block["link"]; ?>'"><?= $block["title"]; ?></button>
                              <?php

                              }
                              else
                              {

                              ?>
                                <a class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" target="_blank" href="<?= $block["link"]; ?>" onclick="removeActiveClass(this);"><?= $block["title"]; ?></a>
                            <?php
                              }
                            }
                            ?>
                            <!---------------------------------------------------------------------------->
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>

                    </div>
                  </div>
                  <div class="card bg-dark" id="defPlyrIsOff" style="display:none;">
                    <div class="card-header border-bottom">
                      <h4 class="text-center text-white"></h4>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-12">
                          <div class="list-group scroll" style="max-height:500px;">
                            <!---------------------------------------------------------------------------->
                            <?php
                            foreach ($episodeslist as $key => $block)
                            {
                              if ($block["link_type"] != 10)
                              {
                            ?>
                                <button class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" onclick="removeActiveClass(this);loadingIframe();
                                document.getElementById('videoIframe').src='<?= str_replace("/On/", "/Off/", $block["link"]); ?>'"><?= $block["title"]; ?></button>
                              <?php

                              }
                              else
                              {

                              ?>
                                <a class="list-group-item list-group-item-action opacity-50 <?= (($key == 0) ? "active" : ""); ?>" target="_blank" href="<?= $block["link"]; ?>" onclick="removeActiveClass(this)"><?= $block["title"]; ?></a>
                            <?php
                              }
                            }
                            ?>
                            <!---------------------------------------------------------------------------->
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>

                    </div>
                  </div>
                </div>
              </div>
            <?php
            }
            else
            {
            ?>
              <div class="row mb-3">
                <div class="col-12">
                  <div class="card bg-dark">
                    <div class="card-header border-bottom">
                      <h4 class="text-center text-white">Megjelenések</h4>
                    </div>
                    <div class="card-body">
                      <iframe id="cboxdiv" src="//animem.org/mininews.php" marginheight="0" marginwidth="0" scrolling="auto" allowtransparency="yes" width="100%" height="380px" frameborder="0"></iframe>
                    </div>
                    <div>
                      <script>
                        setInterval(function() {
                          document.getElementById('cboxdiv').src = '//animem.org/mininews.php';
                        }, 60000);
                      </script>
                    </div>
                  </div>
                </div>
              </div>
            <?php
            }
            ?>

            <div class="row mb-3">
              <div class="col-12">
                <div class="card bg-dark">
                  <div class="card-header border-bottom">
                    <h4 class="text-center text-white">Partnereink:</h4>
                  </div>
                  <div class="card-body px-2">
                    <div class="row mx-1">

                      <!---------------------------------------------------------------------------->
                      <?php
                      $counter = 0;
                      $partner = json_decode(file_get_contents("../Config/banner/partner.json"), true);
                      foreach ($partner as $key => $block)
                      {
                        $counter = ($block["size"] == "1x1") ? $counter + 1 : $counter + 2;
                      ?>
                        <div class="col-<?= (($block["size"] == "1x1") ? "4" : "8"); ?> p-1">
                          <div class="card bg-secondary">
                            <a class="<?= (($block["size"] == "1x1") ? "ratio ratio-1x1" : ""); ?>" href="<?= $block["link"]; ?>" target="_blank">
                              <img class="rounded card-img-top <?= (($block["size"] == "1x1") ? "" : "ratio ratio-1x2"); ?>" src="https://animem.org/Assets/uploads/banner/partner/<?= $block["image"]; ?>" title="<?= $block["name"]; ?>" alt="<?= $block["name"]; ?>" />
                            </a>
                          </div>
                        </div>
                        <?php
                        if ($key == count($partner) - 2 && $counter % 3 == 0)
                        {
                        ?>
                          <div class="col-4 p-1">
                            <div class="card bg-dark border-0">
                              <div class="ratio ratio-1x1">
                                <div class="rounded card-img-top"></div>
                              </div>
                            </div>
                          </div>
                      <?php
                        }
                      }
                      ?>
                      <!---------------------------------------------------------------------------->
                    </div>
                  </div>

                </div>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col-12">
                <div class="card bg-dark">
                  <div class="card-body">
                    <a href="https://www.patreon.com/animem" target="_blank">
                      <img src="https://animem.org/Assets/uploads/fontos_kepek/Patreon.jpg" alt="Patreon" class="card-img-top col-12">
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-12">
            <div class="row mb-3">
              <div class="col-12">