<div class="card bg-dark">
	<div class="card-header border-bottom">
		<h4 class="text-center text-white"><?= $title; ?></h4>
	</div>
	<div class="card-body">
		<div class="row" id="results">

			<!---------------------------------------------------------------------------->
			<?php
			foreach ($mal as $block)
			{
			?>
				<div class="col-lg-3 col-md-6 col-sm-12 mb-4">
					<a class="text-decoration-none" href="https://animem.org/<?= $block["link"]; ?>" title="<?= $block["title"]; ?>">
						<div class="card bg-secondary">
							<div class="card-header">
								<h6 class="text-center text-white col-12 text-truncate"><?= $block["title"]; ?></h6>
							</div>
							<img class="card-img-top" src="<?= $block["img"]; ?>" alt="<?= $block["title"]; ?>" style="height:300px!important;">
						</div>
					</a>
				</div>
			<?php
			}
			?>
			<!---------------------------------------------------------------------------->
		</div>
	</div>
</div>