<div class="rapidwp-box-inside" style="margin-top:10px;">
  <header class="entry-header">
    <div class="entry-header-inside">
      <h1 class="entry-title">
        <?= str_replace("-", " ", $link["title"]); ?>
      </h1>
    </div>
  </header>
  <div class="entry-content clearfix" style="border-bottom:1px solid white; padding-bottom:10px;">
    <div id="jsonzx124">
      <div class="row mx-0">
        <iframe id="jsonzx126" allowfullscreen="" src="//embed.animem.org/Video/Inda/On/<?= $link["link"]; ?>" scrolling="no" style="width: 100%;min-height: 486px;" frameborder="0">
        </iframe>
        <iframe id="jsonzx116" allowfullscreen="" src="https://animem.org/loader.html" scrolling="no" style="width: 100%;min-height: 486px; display:none;" frameborder="0"></iframe>
      </div>
      <label style="text-align: center; width: 49.7%; padding: 0; margin-top: 0px; font-size: 12px;display: inline-block;vertical-align: middle;" class="switch switch-slide">
        <input class="switch-input" type="checkbox" checked="" id="piciricz" onclick="riczropic()">
        <span class="switch-label" data-on="Plyr Be" data-off="Plyr Ki"></span>
        <span class="switch-handle"></span>
      </label>
      <label style="text-align: center; width: 49.7%; padding: 0; margin-top: 0px; font-size: 12px;display: inline-block;vertical-align: middle; background: #333; color: #fff;">
        <span onclick="Copy();">Embed másolása</span>
      </label>
    </div>
  </div>
  <footer class="entry-footer">
    <div class="entry-header-inside" style="vertical-align: top; text-align: center;">
    <span>Készítette a(z) <a class="<?=$link["color"];?>" href="https://animem.org/fansub/?<?= $link["uploaders_id"]; ?>" target="_blank"><?= $link["fname"]; ?></a>.</span>
    </div>
  </footer>
</div>