
  <div class="col-md-3 col-sm-12">
    <?php

    $Widget = [
      [
        "Widget" => "MiniNews",
        "title" => "Megjelenések:"
      ],
      [
        "Widget" => "MiniGallery",
        "title" => "Partnerek:",
        "image" => getBanner(json_decode(fGetCon(FOLDER_CONFIG . "banner" . DS . "partner.json"), true))
      ]
    ];

    viewBuilderWidget($Widget);
    ?>
  </div>