<div class="col-md-3 col-sm-12">
  <?php

  foreach ($value as $SideBarKey => $SideBarValue)
  {

    if (in_array($SideBarKey . ".phtml", findfilefromdir(FOLDER_TEMPLATE . getTheme() . DS . "Widget")))
      if (file_exists(FOLDER_TEMPLATE . getTheme() . DS . "Widget" . DS . $SideBarKey . ".phtml"))
      {
        require_once(FOLDER_TEMPLATE . getTheme() . DS . "Widget" . DS . $SideBarKey . ".phtml");
        if (!empty($SideBarKey) && function_exists($SideBarKey)) call_user_func($SideBarKey, $SideBarValue);
      }
  }
  ?>
</div>