<div class="card bg-dark">
  <div class="card-header border-bottom">
    <h4 class="text-center text-white"><?= $select["title"]; ?></h4>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <div class="col-4">
            <div class="row mt-3">
              <div class="col-1">
              </div>
              <div class="col-10">
                <div class="card">
                  <img src="<?= $response["data"]["images"]["jpg"]["image_url"]; ?>" height="320" />
                </div>
              </div>
              <div class="col-1">
              </div>
            </div>
          </div>
          <div class="col-8">
            <div class="row">
              <div class="col-12">
                <div class="card bg-white text-dark opacity-50">
                  <div class="card-body">
                    <?php

                    foreach ($info as $k => $v)
                    {
                    ?>
                      <div>
                        <div style="vertical-align:top;text-align:left;border-bottom: dotted 1px white;width:99%;display: inline-block;" class="border-bottom">
                          <span style="vertical-align:top;text-align:left;"><?= $k; ?></span>
                          <span style="float:right;" class="ms-3"><?= ($v); ?></span>
                        </div>
                      </div>
                    <?php

                    }
                    ?>

                    <div>
                      <div style="vertical-align:top;text-align:left;width:99%;display: inline-block;">
                        <span style="vertical-align:top;text-align:left;">Fordította:</span>
                        <span style="float:right;"><?= $select["uploaders"]; ?></span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-12">
            <div class="card bg-secondary">
              <div class="card-header">
                <h4>Leírás:</h4>
              </div>
              <div class="card-body">
                <div>
                  <p><?= ($select["description"] == NULL) ? $response["data"]["synopsis"] : $select["description"]; ?></p>
                </div>
              </div>

            </div>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-12">
            <div class="card bg-secondary">
              <!---------------------------------------------------------------------------->
              <?php
              foreach ($select["episodelist"] as $key => $block)
              {
              ?>
                <div class="card-header"><a class="text-white text-decoration-none" href="https://animem.org/<?= $block["type"]; ?>/<?= $block["id"]; ?>/<?= $block["title"]; ?>"><?= $block["title"]; ?></a></div>
              <?php
              }
              ?>
              <!---------------------------------------------------------------------------->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>