</div>
</div>
</div>

<div class="col-md-3 col-sm-12">
  <div class="row mb-3">
    <div class="col-12">
      <div class="card bg-dark">
        <div class="card-header border-bottom">
          <h4 class="text-center text-white">Csatlakozz a közösséghez!</h4>
        </div>
        <div class="card-body px-2">
          <div class="row mx-2">
            <div class="col-4 p-1">
              <div class="card bg-secondary">
                <a class="ratio ratio-1x1" href="//animem.org/Discord" target="_blank">
                  <img class="rounded card-img-top" src="https://animem.org/Assets/uploads/banner/other/Discord.jpg" title="Discord" alt="Discord" />
                </a>
              </div>
            </div>
            <div class="col-4 p-1">
              <div class="card bg-secondary">
                <a class="ratio ratio-1x1" href="https://www.facebook.com/animem.org" target="_blank">
                  <img class="rounded card-img-top" src="https://animem.org/Assets/uploads/banner/other/Facebook.jpg" title="Facebook" alt="Facebook" />
                </a>
              </div>
            </div>
            <div class="col-4 p-1">
              <div class="card bg-secondary">
                <a class="ratio ratio-1x1" href="https://www.instagram.com/animem_hun/" target="_blank">
                  <img class="rounded card-img-top" src="https://animem.org/Assets/uploads/banner/other/Instagram.jpg" title="Instagram" alt="Instagram" />
                </a>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-12">
      <div class="card bg-dark">
        <div class="card-header border-bottom">
          <h4 class="text-center text-white">Kiemelt FanSub-ok:</h4>
        </div>
        <div class="card-body px-2">
          <div class="row mx-1">

            <!---------------------------------------------------------------------------->
            <?php
            $counter = 0;
            $high = json_decode(file_get_contents("../Config/banner/high.json"), true);
            foreach ($high as $key => $block)
            {
              $counter = ($block["size"] == "1x1") ? $counter + 1 : $counter + 2;
            ?>
              <div class="col-<?= (($block["size"] == "1x1") ? "4" : "8"); ?> p-1">
                <div class="card bg-secondary">
                  <a class="<?= (($block["size"] == "1x1") ? "ratio ratio-1x1" : ""); ?>" href="<?= $block["link"]; ?>" target="_blank">
                    <img class="rounded card-img-top <?= (($block["size"] == "1x1") ? "" : "ratio ratio-1x2"); ?>" src="https://animem.org/Assets/uploads/banner/high/<?= $block["image"]; ?>" title="<?= $block["name"]; ?>" alt="<?= $block["name"]; ?>" />
                  </a>
                </div>
              </div>
              <?php
              if ($key == count($high) - 2 && $counter % 3 == 0)
              {
              ?>
                <div class="col-4 p-1">
                  <div class="card bg-dark border-0">
                    <div class="ratio ratio-1x1">
                      <div class="rounded card-img-top"></div>
                    </div>
                  </div>
                </div>
            <?php
              }
            }
            ?>
            <!---------------------------------------------------------------------------->
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12">
      <div class="card bg-dark">
        <div class="card-body">
          <a href="https://www.patreon.com/animem" target="_blank">
            <img src="https://animem.org/Assets/uploads/fontos_kepek/Patreon.jpg" alt="Patreon" class="card-img-top col-12">
          </a>
        </div>
      </div>
    </div>
  </div>


</div>
</div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <div class="card bg-dark">
      <div class="card-body px-2 text-center text-white">
        <div class="row mb-3">
          <div class="col-12"><i id="demo" style="display: block;"></i>
            <span><?php
                  $diff = date_diff(date_create("2009-10-23"), date_create(date("Y-m-d")));

                  echo "Már " . $diff->y . " éve, " . $diff->m . " hónapja és " . $diff->d . " napja csak értetek.";

                  ?></span><br />
            <span>Az elmúlt 30 percben online látogatók: <?= onlineUsers($conn); ?></span>
          </div>
        </div>
        <div class="row mb-3">
          <span>Jellenlegi verzió: <a href="https://animem.org/ChangeLog"><?= VERSION;?></a></span>
        </div>
        <!--div class="row mb-3">
          <h5>Válts témát:</h5>
          <span>Jellenlegi téma: <?= str_replace([".min.css", "bootstrap"], ["", "Original"], (isset($_COOKIE["template"])) ? $template[$_COOKIE["template"]] : "Superhero.min.css"); ?></span>
          <span>Alap téma: Superhero</span>
          <div class="col-12">
            <?php
            foreach ($template as $key => $value)
            {
            ?>
              <span><a class="text-decoration-none" href="https://animem.org/Template/<?= $key; ?>"><?= str_replace([".min.css", "bootstrap"], ["", "Original"], $value); ?></a></span>
            <?php
            }
            ?>
          </div>
        </div-->
      </div>

    </div>
  </div>
</div>
</div>

<script>
  let ratio = [16, 9];

  function jsonzx122() {
    if (typeof GEBI('divR17') !== 'undefined' && GEBI('divR17') !== null)
      alert('' +
        'A következő tartalom kiskorúak számára káros lehet. \n' +
        'Az alábbi animét csak 18. életévét betöltött személyeknek ajánljuk!\n' +
        'Az anime \'R-17+\' beorolású az-az tartalmazhat erőszakot és trágár beszédet!');
    else if (typeof GEBI('divRX') !== 'undefined' && GEBI('divRX') !== null)
      alert('' +
        'A következő tartalom kiskorúak számára káros lehet. \n' +
        'Az alábbi animét csak 18. életévét betöltött személyeknek ajánljuk!\n' +
        'Az anime \'Rx\' beorolású az-az tartalmaz Hentai-t (extrém szexuális tartalom / meztelenség)!');
    else if (typeof GEBI('divRP') !== 'undefined' && GEBI('divRP') !== null)
      alert('' +
        'A következő tartalom kiskorúak számára káros lehet. \n' +
        'Az alábbi animét csak 18. életévét betöltött személyeknek ajánljuk!\n' +
        'Az anime \'R+\' beorolású az-az tartalmazhat "Enyhe meztelenséget", illetve erőszakot és trágár beszédet!');
  }





  // Set the date we're counting down to
  /*var countDownDate = new Date("Aug 18, 2022 00:00:00").getTime();
  // Update the count down every 1 second
  var x = setInterval(function() {
    // Get today's date and time
    var now = new Date().getTime();
    // Find the distance between now and the count down date
    var distance = countDownDate - now;
    document.getElementById("demo").innerHTML =  (Math.floor((1761170400000 - now) / 1000) - 31536000);
    distance = 0;
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
   // var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    var seconds = Math.floor(distance / 1000);
    // Display the result in the element with id="demo"
    //document.getElementById("demo").innerHTML =  Math.floor((1761170400000 - now) / 1000);
    // If the count down is finished, write some text
    if (distance < 0) {
      clearInterval(x);
      document.getElementById("demo").innerHTML = "EXPIRED";
    }
  }, 1000);*/



  function jsonzx100() {
    loadingIframe();
    jsonzx122();
  }

  window.onload = jsonzx100();
  let frameWidth = 0;
  jQuery(window).resize(function() {
    //console.log("window resize");
    //console.log(GEBI('videoIframe').offsetWidth);
    //GEBI('videoIframe').offsetWidth;
    if (GEBI('videoIframe').offsetWidth) {
      frameWidth = 0;
    }

    if (typeof GEBI('videoIframe') !== 'undefined' && GEBI('videoIframe') !== null)
    GEBI('videoIframe').style.height = ((GEBI('videoIframe').offsetWidth / ratio[0]) * ratio[1]) + "px";

    if (typeof GEBI('loadingIframe') !== 'undefined' && GEBI('loadingIframe') !== null)
    GEBI('loadingIframe').style.height = ((GEBI('loadingIframe').offsetWidth / ratio[0]) * ratio[1]) + "px";

    //jQuery('.videoIframe').width("200px");
  });

  function GEBI(X) {
    return document.getElementById(X);
  }

  function jsonzx102() {
    document.getElementById("jsonzx126").style.display = 'none';
    document.getElementById("jsonzx116").style.display = 'block';
    document.getElementById("jsonzx126").addEventListener("load", function(e) {
      // alert(this.nodeName);
      document.getElementById("jsonzx126").style.display = 'block';
      document.getElementById("jsonzx116").style.display = 'none';
      console.log(e.target);
    });
  }



  function jsonzx120(str) // counter
  {
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        console.log(this.responseText);
        document.getElementById("jsonzx128").innerHTML = "Megtekintette " + this.responseText + " ember.";
      }
    }
    xmlhttp.open("GET", "https://animem.org/counter.php?q=" + str, true);
    xmlhttp.send();
  }

  function loadingIframe() {

    if (typeof GEBI('loadingIframe') !== 'undefined' && GEBI('loadingIframe') !== null){
    if (GEBI('loadingIframe').offsetWidth < GEBI('videoIframe').offsetWidth)
      videoWidth = GEBI('videoIframe').offsetWidth;
    else
    if (GEBI('loadingIframe').offsetWidth > GEBI('videoIframe').offsetWidth)
      videoWidth = GEBI('loadingIframe').offsetWidth;
    else
      videoWidth = 720;
    GEBI('videoIframe').style.height = ((videoWidth / ratio[0]) * ratio[1]) + "px";
    GEBI('loadingIframe').style.height = ((videoWidth / ratio[0]) * ratio[1]) + "px";
    document.getElementById("videoIframe").style.display = 'none';
    document.getElementById("loadingIframe").style.display = 'block';
    document.getElementById("videoIframe").addEventListener("load", function(e) {
      // alert(this.nodeName);
      document.getElementById("videoIframe").style.display = 'block';
      document.getElementById("loadingIframe").style.display = 'none';
      videoWidth = (GEBI('videoIframe').offsetWidth + 1);
      GEBI('videoIframe').style.width = videoWidth + "px";
      videoWidth = (GEBI('videoIframe').offsetWidth - 1);
      GEBI('videoIframe').style.width = videoWidth + "px";
      //console.log(e.target);
    });}
    else{
      
    }

  }


  function SwitchPlyr() {
    if (GEBI("SwitchPlyr").checked == true) {
      loadingIframe();
      GEBI("videoIframe").src = GEBI("videoIframe").src.replace('/Off/', '/On/');
      GEBI("defPlyrIsOn").style.display = "block";
      GEBI("defPlyrIsOff").style.display = "none";
      GEBI("SwitchPlyrButton").innerHTML = "Plyr Be";
      GEBI("SwitchPlyrButton").classList.toggle('btn-success');
      GEBI("SwitchPlyrButton").classList.toggle('btn-secondary');
    } else {
      loadingIframe();
      GEBI("videoIframe").src = GEBI("videoIframe").src.replace('/On/', '/Off/');
      GEBI("defPlyrIsOn").style.display = "none";
      GEBI("defPlyrIsOff").style.display = "block";
      GEBI("SwitchPlyrButton").innerHTML = "Plyr Ki";
      GEBI("SwitchPlyrButton").classList.toggle('btn-success');
      GEBI("SwitchPlyrButton").classList.toggle('btn-secondary');
    }
  }

  function CopyIframe() {
    let textarea = GEBI("videoIframe");
    let div = GEBI("jsonzx124");
    textarea = textarea.outerHTML;
    textarea = textarea.replace(' id="videoIframe"', '').replace(/\u00a0/g, " ");
    textarea = textarea.replace(/\u00a0/g, " ");
    textarea = textarea.replace('x-anime.hu/streaming/', 'x-anime.hu/player/');

    textarea = textarea.replace(".mp4", '');
    textarea = textarea.replace("display:none;", '');
    if (typeof GEBI("copybox") === 'undefined' || GEBI("copybox") === null) {
      div.innerHTML += '<textarea id="copybox">' + textarea + '</textarea>';
    } else {
      GEBI("copybox").innerHTML = textarea;
    }
    let copyTextarea = GEBI("copybox");
    copyTextarea.style = "display: block;"; //select the text area
    copyTextarea.select(); //select the text area
    copyTextarea.setSelectionRange(0, 99999);
    document.execCommand("copy"); //copy to clipboard
    /* Alert the copied text */
    alert("Copied the text: \n" + copyTextarea.value);
    copyTextarea.style = "display: none;"; //select the text area
  }
  function removeActiveClass(e) {

    let elements = e.parentNode.getElementsByClassName('active');
    while (elements.length > 0) {
      elements[0].classList.remove('active');
    }
    e.classList.add('active');
  }

</script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
