
<div class="row mb-3">
  <div class="col-12">
    <div class="card bg-dark">
      <div class="card-body px-2 text-center text-white">
        <div class="row mb-3">
          <div class="col-12"><i id="demo" style="display:none;"></i>
            <span><?php
                  $diff = date_diff(date_create("2009-10-23"), date_create(date("Y-m-d")));

                  echo "Már " . $diff->y . " éve, " . $diff->m . " hónapja és " . $diff->d . " napja csak értetek.";

                  ?></span><br />
            <span>Mai Látogatók: <?php echo todayUsers($conn); ?></span><br />
            <span>Online Látogatók: <?php echo onlineUsers($conn); ?></span>
          </div>
        </div>
        <div class="row mb-3">
          <h5>Válts témát:</h5>
          <span>Jellenlegi téma: <?= str_replace([".min.css", "bootstrap"], ["", "Original"], (isset($_COOKIE["template"]))?$template[$_COOKIE["template"]]:"Superhero.min.css"); ?></span>
          <span>Alap téma: Superhero</span>
          <div class="col-12">
          <?php
          foreach ($template as $key => $value) {
            ?>
            <span><a class="text-decoration-none" href="https://animem.org/Template/<?= $key; ?>"><?= str_replace([".min.css", "bootstrap"], ["", "Original"], $value); ?></a></span>
          <?php
          }
          ?>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
</div>

<script>
  function Copy() {
    let textarea = document.getElementById("jsonzx126");
    let div = document.getElementById("jsonzx124");
    textarea = textarea.outerHTML;
    textarea = textarea.replace(' id="jsonzx126"', '');
    if (typeof document.getElementById("copybox") === 'undefined' || document.getElementById("copybox") === null) {
      div.innerHTML += '<textarea id="copybox">' + textarea + '</textarea>';
    } else {
      document.getElementById("copybox").innerHTML = textarea;
    }
    let copyTextarea = document.getElementById("copybox");
    copyTextarea.style = "display: block;"; //select the text area
    copyTextarea.select(); //select the text area
    copyTextarea.setSelectionRange(0, 99999);
    document.execCommand("copy"); //copy to clipboard
    /* Alert the copied text */
    alert("Copied the text: \n" + copyTextarea.value);
    copyTextarea.style = "display: none;"; //select the text area
  }
  // Set the date we're counting down to
  var countDownDate = new Date("Sep 18, 2022 00:00:00").getTime();
  // Update the count down every 1 second
  var x = setInterval(function() {
    // Get today's date and time
    var now = new Date().getTime();
    // Find the distance between now and the count down date
    var distance = countDownDate - now;
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    // Display the result in the element with id="demo"
    document.getElementById("demo").innerHTML = days + " Nap " + hours + " Óra " + minutes + " Perc " + seconds + " Másodperc és Hellmesternek születés napja lesz!";
    // If the count down is finished, write some text
    if (distance < 0) {
      clearInterval(x);
      document.getElementById("demo").innerHTML = "EXPIRED";
    }
  }, 1000);

  function GEBI(X) {
    return document.getElementById(X);
  }
  function jsonzx100() {
    loadingIframe();
  }



  function jsonzx102() {
    document.getElementById("jsonzx126").style.display = 'none';
    document.getElementById("jsonzx116").style.display = 'block';
    document.getElementById("jsonzx126").addEventListener("load", function(e) {
      // alert(this.nodeName);
      document.getElementById("jsonzx126").style.display = 'block';
      document.getElementById("jsonzx116").style.display = 'none';
      console.log(e.target);
    });
  }



  function jsonzx120(str) // counter
  {
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        console.log(this.responseText);
        document.getElementById("jsonzx128").innerHTML = "Megtekintette " + this.responseText + " ember.";
      }
    }
    xmlhttp.open("GET", "https://animem.org/counter.php?q=" + str, true);
    xmlhttp.send();
  }

  function loadingIframe() {
    document.getElementById("videoIframe").style.display = 'none';
    document.getElementById("loadingIframe").style.display = 'block';
    document.getElementById("videoIframe").addEventListener("load", function(e) {
      // alert(this.nodeName);
      document.getElementById("videoIframe").style.display = 'block';
      document.getElementById("loadingIframe").style.display = 'none';
      //console.log(e.target);
    });
  }

  function SwitchPlyr() {
    if (GEBI("SwitchPlyr").checked == true) {
      loadingIframe();
      GEBI("videoIframe").src = GEBI("videoIframe").src.replace('/Off/', '/On/');
      GEBI("defPlyrIsOn").style.display = "block";
      GEBI("defPlyrIsOff").style.display = "none";
      GEBI("SwitchPlyrButton").innerHTML = "Plyr Be";
      GEBI("SwitchPlyrButton").classList.toggle('btn-success');
      GEBI("SwitchPlyrButton").classList.toggle('btn-secondary');
    } else {
      loadingIframe();
      GEBI("videoIframe").src = GEBI("videoIframe").src.replace('/On/', '/Off/');
      GEBI("defPlyrIsOn").style.display = "none";
      GEBI("defPlyrIsOff").style.display = "block";
      GEBI("SwitchPlyrButton").innerHTML = "Plyr Ki";
      GEBI("SwitchPlyrButton").classList.toggle('btn-success');
      GEBI("SwitchPlyrButton").classList.toggle('btn-secondary');
    }
  }

  function CopyIframe() {
    let textarea = GEBI("videoIframe");
    let div = GEBI("jsonzx124");
    textarea = textarea.outerHTML;
    textarea = textarea.replace(' id="videoIframe"', '');
    if (typeof GEBI("copybox") === 'undefined' || GEBI("copybox") === null) {
      div.innerHTML += '<textarea id="copybox">' + textarea + '</textarea>';
    } else {
      GEBI("copybox").innerHTML = textarea;
    }
    let copyTextarea = GEBI("copybox");
    copyTextarea.style = "display: block;"; //select the text area
    copyTextarea.select(); //select the text area
    copyTextarea.setSelectionRange(0, 99999);
    document.execCommand("copy"); //copy to clipboard
    /* Alert the copied text */
    alert("Copied the text: \n" + copyTextarea.value);
    copyTextarea.style = "display: none;"; //select the text area
  }


  function removeActiveClass(e) {

    let elements = e.parentNode.getElementsByClassName('active');
    while (elements.length > 0) {
      elements[0].classList.remove('active');
    }
    e.classList.add('active');
  }


  window.onload = jsonzx100();
</script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>